#!/usr/bin/env python3
"""
Autosvar Filter - Move automated response emails to AUTOMATED folder

Scans INBOX for emails with "autosvar" (Swedish auto-reply) or other
automated response indicators in subject/headers, and moves them to AUTOMATED folder.

Supports:
- Gmail accounts (imap.gmail.com)
- A2 Hosting accounts (nl1-cl8-ats1.a2hosting.com)

Usage:
    python3 autosvar_filter.py                    # Process all accounts
    python3 autosvar_filter.py --account gmail    # Only Gmail
    python3 autosvar_filter.py --account a2       # Only A2 accounts
    python3 autosvar_filter.py --dry-run          # Show what would be moved
    python3 autosvar_filter.py --status           # Show account status
    python3 autosvar_filter.py --stats            # Show detection statistics
"""

import imaplib
import email
import os
import sys
import argparse
import json
import logging
from datetime import datetime
from pathlib import Path
from email.header import decode_header
from dotenv import load_dotenv
from collections import defaultdict
import re
import requests

load_dotenv('/opt/ACTIVE/EMAIL/CAMPAIGNS/.env')

# Setup logging
LOG_DIR = Path('/opt/ACTIVE/INFRA/LOGS/autosvar_filter')
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_FILE = LOG_DIR / 'autosvar_filter.log'
STATS_FILE = LOG_DIR / 'stats.json'
UNSUBSCRIBE_FILE = LOG_DIR / 'unsubscribe_links.txt'
BLOCKED_SENDERS_FILE = LOG_DIR / 'blocked_senders.txt'
UNSUBSCRIBE_LOG = LOG_DIR / 'unsubscribe_results.log'

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)

# Additional headers that indicate auto-replies (expanded detection)
# NOTE: X-Auto-Response-Suppress removed - used by marketing emails (Kiwi.com, Perplexity, etc.)
AUTOREPLY_HEADERS = [
    'X-Autoreply',
    'X-Autorespond',                  # Some mail servers
    'X-MS-Exchange-Generated-Message-Source',  # Exchange OOF
    'X-Autogenerated',                # Auto-generated messages
    'X-AutoReply-From',               # Some corporate systems
]

# Sender patterns that indicate auto-replies
AUTOREPLY_SENDER_PATTERNS = [
    'noreply-autoreply@',
    'auto-reply@',
    'autoreply@',
    'vacation@',
    'ooo@',
    'out-of-office@',
    'autoresponder@',
    'do-not-reply@',
    'donotreply@',
]

# Keywords indicating automated responses
AUTOSVAR_KEYWORDS = [
    'autosvar',           # Swedish
    'automatiskt svar',   # Swedish
    'auto-reply',
    'automatic reply',
    'out of office',
    'out-of-office',
    'ooo:',
    'abwesenheitsnotiz',  # German
    'automatische antwort',  # German
    'reponse automatique',   # French
    'risposta automatica',   # Italian
    'respuesta automatica',  # Spanish
    'automatisch antwoord',  # Dutch
    'automaattinen vastaus', # Finnish
    'automatisk svar',       # Norwegian/Danish
]

# Email accounts configuration
ACCOUNTS = {
    # Gmail accounts
    'manpowerdristor@gmail.com': {
        'server': 'imap.gmail.com',
        'port': 993,
        'password_env': 'GMAIL_APP_PASSWORD',
        'type': 'gmail'
    },
    'manpower.dristor@gmail.com': {
        'server': 'imap.gmail.com',
        'port': 993,
        'password_env': 'GMAIL_MANPOWER_APP_PASSWORD',
        'type': 'gmail'
    },
    'elena.manpower.dristor@gmail.com': {
        'server': 'imap.gmail.com',
        'port': 993,
        'password_env': 'GMAIL_ELENA_PASSWORD',
        'type': 'gmail'
    },
    'expatsinromania@gmail.com': {
        'server': 'imap.gmail.com',
        'port': 993,
        'password_env': 'GMAIL_EXPATS_PASSWORD',
        'type': 'gmail'
    },
    'cumparlegume@gmail.com': {
        'server': 'imap.gmail.com',
        'port': 993,
        'password_env': 'GMAIL_CUMPARLEGUME_PASSWORD',
        'type': 'gmail'
    },
    'casafaurbucuresti@gmail.com': {
        'server': 'imap.gmail.com',
        'port': 993,
        'password_env': 'GMAIL_CASAFAUR_PASSWORD',
        'type': 'gmail'
    },
    'fruitnature4@gmail.com': {
        'server': 'imap.gmail.com',
        'port': 993,
        'password_env': 'GMAIL_SEARCH_PASSWORD',
        'type': 'gmail'
    },
    # A2 Hosting accounts
    'office@horecaworkers.eu': {
        'server': 'nl1-cl8-ats1.a2hosting.com',
        'port': 993,
        'password_env': 'A2_HORECAWORKERS_EU_PASSWORD',
        'type': 'a2'
    },
    'office@meatworkers.eu': {
        'server': 'nl1-cl8-ats1.a2hosting.com',
        'port': 993,
        'password_env': 'A2_MEATWORKERS_EU_PASSWORD',
        'type': 'a2'
    },
    'office@electricjobs.eu': {
        'server': 'nl1-cl8-ats1.a2hosting.com',
        'port': 993,
        'password_env': 'A2_ELECTRICJOBS_EU_PASSWORD',
        'type': 'a2'
    },
    'office@mechanicjobs.eu': {
        'server': 'nl1-cl8-ats1.a2hosting.com',
        'port': 993,
        'password_env': 'A2_MECHANICJOBS_EU_PASSWORD',
        'type': 'a2'
    },
    'office@farmworkers.eu': {
        'server': 'nl1-cl8-ats1.a2hosting.com',
        'port': 993,
        'password_env': 'A2_FARMWORKERS_EU_PASSWORD',
        'type': 'a2'
    },
    'office@factoryjobs.eu': {
        'server': 'nl1-cl8-ats1.a2hosting.com',
        'port': 993,
        'password_env': 'A2_FACTORYJOBS_EU_PASSWORD',
        'type': 'a2'
    },
    'office@warehouseworkers.eu': {
        'server': 'nl1-cl8-ats1.a2hosting.com',
        'port': 993,
        'password_env': 'A2_WAREHOUSEWORKERS_EU_PASSWORD',
        'type': 'a2'
    },
    'office@horecaworkers2026.eu': {
        'server': 'nl1-cl8-ats1.a2hosting.com',
        'port': 993,
        'password_env': 'A2_HORECAWORKERS2026_EU_PASSWORD',
        'type': 'a2'
    },
    'office@horecaworkers2026.com': {
        'server': 'nl1-cl8-ats1.a2hosting.com',
        'port': 993,
        'password_env': 'A2_HORECAWORKERS2026_COM_PASSWORD',
        'type': 'a2'
    },
    'office@horecaworkers2026.online': {
        'server': 'nl1-cl8-ats1.a2hosting.com',
        'port': 993,
        'password_env': 'A2_HORECAWORKERS2026_ONLINE_PASSWORD',
        'type': 'a2'
    },
    # Yahoo accounts
    'apaminerala@yahoo.com': {
        'server': 'imap.mail.yahoo.com',
        'port': 993,
        'password_env': 'YAHOO_APAMINERALA_APP_PASSWORD',
        'type': 'yahoo'
    },
}

TARGET_FOLDER_AUTOSVAR = 'AUTOMATED'
TARGET_FOLDER_BOUNCES = 'BOUNCES'
TARGET_FOLDER_MARKETING = 'MARKETING'

# Known marketing senders - move to MARKETING folder
MARKETING_SENDERS = [
    # Travel/booking
    'kiwi.com', 'booking.com', 'expedia', 'trivago', 'skyscanner', 'kayak.com',
    'airbnb', 'hotels.com', 'tripadvisor',
    # Tech/SaaS marketing
    'perplexity', 'mightytext', 'signwell', 'mailchimp', 'hubspot', 'salesforce',
    'zapier', 'notion', 'slack', 'asana', 'trello', 'monday.com', 'clickup',
    'canva', 'grammarly', 'dropbox', 'evernote', 'zoom.us',
    # Email tools marketing
    'zerobounce', 'neverbounce', 'emaillistchecker', 'hunter.io', 'snov.io',
    'lemlist', 'woodpecker', 'mailshake', 'apollo.io', 'lusha', 'clearbit',
    # Social/newsletters
    'substack', 'medium.com', 'linkedin', 'twitter.com', 'x.com',
    # Shopping/deals
    'groupon', 'aliexpress', 'amazon', 'ebay', 'wish.com',
    # CRM/marketing platforms
    'minicrm', 'freshworks', 'freshservice', 'zendesk', 'intercom',
    'activecampaign', 'getresponse', 'convertkit', 'drip.com',
    # Romanian marketing
    'irigam.ro', 'emag.ro', 'olx.ro', 'publi24',
    # WordPress notifications (comment spam, updates)
    'wordpress@', 'wordpress.com', 'wordpress.org',
    # Generic marketing patterns
    'newsletter@', 'marketing@', 'promo@', 'offers@', 'deals@', 'info@',
    'news@', 'updates@', 'noreply@', 'no-reply@', 'donotreply@',
]

# Subject patterns that indicate marketing
MARKETING_SUBJECT_PATTERNS = [
    'black friday', 'cyber monday', 'flash sale', '% off', 'discount',
    'limited time', 'act now', 'don\'t miss', 'last chance', 'expires',
    'unsubscribe', 'free trial', 'special offer', 'exclusive deal',
    'upgrade now', 'buy now', 'shop now', 'order now', 'claim your',
    'win a', 'congratulations', 'you\'ve been selected', 'you won',
]

# Keywords indicating bounces (separate from regular auto-replies)
BOUNCE_KEYWORDS = [
    'mail delivery failed',
    'delivery failed',
    'delivery status',
    'undelivered mail',
    'undeliverable',
    'returned to sender',
    'could not be delivered',
    'delivery failure',
    'message could not be delivered',
    'failed to deliver',
    'bounce',
    'mailer-daemon',
    'postmaster',
]


def decode_subject(msg):
    """Decode email subject, handling various encodings."""
    subject = msg.get('Subject', '')
    if not subject:
        return ''

    try:
        decoded_parts = decode_header(subject)
        decoded_subject = ''
        for part, encoding in decoded_parts:
            if isinstance(part, bytes):
                decoded_subject += part.decode(encoding or 'utf-8', errors='ignore')
            else:
                decoded_subject += part
        return decoded_subject.lower()
    except:
        return str(subject).lower()


def is_bounce(msg):
    """Check if email is a bounce/delivery failure."""
    subject = decode_subject(msg)
    from_addr = msg.get('From', '').lower()

    # Skip known marketing senders that use bounce-related words
    marketing_senders = ['zerobounce', 'neverbounce', 'bounceless', 'debounce']
    if any(sender in from_addr for sender in marketing_senders):
        return False, None

    # Check subject for bounce keywords
    for keyword in BOUNCE_KEYWORDS:
        if keyword in subject:
            return True, f"subject contains '{keyword}'"

    # Check from address for mailer-daemon/postmaster
    if 'mailer-daemon' in from_addr or 'postmaster' in from_addr:
        return True, f"from: {from_addr}"

    return False, None


def is_social_media_spam(msg):
    """Check if email is from social media (Facebook, Instagram, etc.) - SKIP these."""
    from_addr = msg.get('From', '').lower()
    subject = decode_subject(msg)

    # Skip Facebook/Meta
    if 'facebook' in from_addr or 'facebookmail' in from_addr or 'meta.com' in from_addr:
        return True
    if 'notification@' in from_addr and ('fb' in from_addr or 'facebook' in from_addr):
        return True

    # Skip Instagram
    if 'instagram' in from_addr or 'ig.com' in from_addr:
        return True

    # Skip by subject patterns
    social_patterns = [
        'new friend suggestion',
        'started following you',
        'catch up on moments',
        'see what\'s been happening',
        'notifications about',
        'new group suggest',
        'new page suggest',
        'reels of the day',
        'mentioned you on facebook',
        'vezi momentele pe care le-ai ratat',
        'vezi conţinut de la',
        'a distribuit ceva nou',
        'elmojoman',
        'see reels from',
    ]
    for pattern in social_patterns:
        if pattern in subject:
            return True

    # Skip Mailtrack marketing emails
    if 'mailtrack' in from_addr or 'mailtrack' in subject:
        return True

    return False


def is_autosvar(msg):
    """Check if email is a BUSINESS automated response (non-bounce)."""
    # First check if it's a bounce - bounces go to separate folder
    is_bounce_email, _ = is_bounce(msg)
    if is_bounce_email:
        return False, None  # Let is_bounce handle this

    # Skip social media notifications - NOT business emails
    if is_social_media_spam(msg):
        return False, None

    from_addr = msg.get('From', '').lower()

    # Check sender patterns first (high confidence)
    for pattern in AUTOREPLY_SENDER_PATTERNS:
        if pattern in from_addr:
            return True, f"sender pattern: {pattern}"

    # Check subject for business auto-reply keywords
    subject = decode_subject(msg)
    for keyword in AUTOSVAR_KEYWORDS:
        if keyword in subject:
            return True, f"subject contains '{keyword}'"

    # Check Auto-Submitted header (RFC 3834) - but only if from business domain
    auto_submitted = msg.get('Auto-Submitted', '').lower()
    if auto_submitted and auto_submitted != 'no':
        # Only count if NOT from known marketing/social senders
        if not any(x in from_addr for x in ['noreply', 'no-reply', 'mailtrack', 'facebook', 'instagram', 'meta.com']):
            return True, f"Auto-Submitted: {auto_submitted}"

    # Check all auto-reply headers (expanded detection)
    for header in AUTOREPLY_HEADERS:
        header_value = msg.get(header)
        if header_value:
            return True, f"{header} header present"

    # Check Precedence header
    precedence = msg.get('Precedence', '').lower()
    if precedence in ['auto_reply', 'autoreply', 'auto-reply']:
        return True, f"Precedence: {precedence}"

    return False, None


def is_marketing(msg):
    """Check if email is marketing/promotional."""
    from_addr = msg.get('From', '').lower()
    subject = decode_subject(msg)

    # Check sender against known marketing senders
    for sender in MARKETING_SENDERS:
        if sender in from_addr:
            return True, f"marketing sender: {sender}"

    # Check for X-Auto-Response-Suppress header (used by marketing platforms)
    if msg.get('X-Auto-Response-Suppress'):
        return True, "X-Auto-Response-Suppress header (marketing)"

    # Check subject for marketing patterns
    for pattern in MARKETING_SUBJECT_PATTERNS:
        if pattern in subject:
            return True, f"marketing subject: {pattern}"

    # Check for List-Unsubscribe header (newsletters/marketing)
    if msg.get('List-Unsubscribe'):
        # Only if also has other marketing indicators
        if any(x in from_addr for x in ['newsletter', 'marketing', 'promo', 'news@', 'info@']):
            return True, "List-Unsubscribe + marketing sender"

    return False, None


def extract_unsubscribe_link(msg):
    """Extract unsubscribe URL from List-Unsubscribe header."""
    header = msg.get('List-Unsubscribe', '')
    if not header:
        return None, None

    # Parse List-Unsubscribe header which can contain:
    # <http://...>, <mailto:...>, or both
    http_match = re.search(r'<(https?://[^>]+)>', header)
    mailto_match = re.search(r'<(mailto:[^>]+)>', header)

    http_url = http_match.group(1) if http_match else None
    mailto_url = mailto_match.group(1) if mailto_match else None

    return http_url, mailto_url


def save_blocked_sender(from_addr, subject, reason):
    """Save sender to blocked senders file."""
    try:
        # Extract email from "Name <email>" format
        email_match = re.search(r'<([^>]+)>', from_addr)
        sender_email = email_match.group(1) if email_match else from_addr

        # Extract domain
        domain = sender_email.split('@')[-1] if '@' in sender_email else sender_email

        with open(BLOCKED_SENDERS_FILE, 'a') as f:
            f.write(f"{datetime.now().isoformat()}|{sender_email}|{domain}|{subject[:50]}|{reason}\n")
    except Exception as e:
        logger.error(f"Could not save blocked sender: {e}")


def auto_unsubscribe(http_url, mailto_url, from_addr, subject):
    """Attempt to automatically unsubscribe from mailing list."""
    result = None

    # Try HTTP unsubscribe first (preferred - one-click)
    if http_url:
        try:
            # Some unsubscribe links use POST, but many accept GET
            headers = {
                'User-Agent': 'Mozilla/5.0 (compatible; EmailUnsubscriber/1.0)',
                'Accept': 'text/html,application/xhtml+xml'
            }
            resp = requests.get(http_url, headers=headers, timeout=10, allow_redirects=True)

            if resp.status_code in [200, 202, 204]:
                result = f"SUCCESS:HTTP:{resp.status_code}"
                logger.info(f"UNSUBSCRIBED | {from_addr} | {http_url[:60]} | HTTP {resp.status_code}")
            else:
                result = f"FAILED:HTTP:{resp.status_code}"
                logger.warning(f"UNSUB_FAILED | {from_addr} | {http_url[:60]} | HTTP {resp.status_code}")
        except requests.exceptions.Timeout:
            result = "FAILED:HTTP:TIMEOUT"
        except requests.exceptions.RequestException as e:
            result = f"FAILED:HTTP:{str(e)[:30]}"

    # Log mailto for manual processing if HTTP failed or unavailable
    if mailto_url and (not result or result.startswith('FAILED')):
        try:
            with open(UNSUBSCRIBE_FILE, 'a') as f:
                f.write(f"{datetime.now().isoformat()}|{from_addr}|{mailto_url}|{subject[:50]}\n")
            if not result:
                result = "LOGGED:MAILTO"
        except Exception as e:
            logger.error(f"Could not log mailto: {e}")

    # Log to unsubscribe results
    try:
        with open(UNSUBSCRIBE_LOG, 'a') as f:
            f.write(f"{datetime.now().isoformat()}|{from_addr}|{result or 'NO_LINK'}|{subject[:50]}\n")
    except:
        pass

    return result


def load_stats():
    """Load statistics from file."""
    if STATS_FILE.exists():
        try:
            with open(STATS_FILE, 'r') as f:
                return json.load(f)
        except:
            pass
    return {
        'total_processed': 0,
        'total_autosvar': 0,
        'total_bounces': 0,
        'total_marketing': 0,
        'by_account': {},
        'by_reason': defaultdict(int),
        'by_date': {},
        'last_run': None
    }


def save_stats(stats):
    """Save statistics to file."""
    # Convert defaultdict to regular dict for JSON serialization
    if isinstance(stats.get('by_reason'), defaultdict):
        stats['by_reason'] = dict(stats['by_reason'])
    stats['last_run'] = datetime.now().isoformat()
    with open(STATS_FILE, 'w') as f:
        json.dump(stats, f, indent=2)


def update_stats(stats, account, reason, email_type):
    """Update statistics with a detection."""
    today = datetime.now().strftime('%Y-%m-%d')

    # Initialize account stats if needed
    if account not in stats['by_account']:
        stats['by_account'][account] = {'autosvar': 0, 'bounces': 0, 'marketing': 0}

    # Ensure marketing key exists (for old stats files)
    if 'marketing' not in stats['by_account'][account]:
        stats['by_account'][account]['marketing'] = 0
    if 'total_marketing' not in stats:
        stats['total_marketing'] = 0

    # Update counters
    if email_type == 'autosvar':
        stats['total_autosvar'] += 1
        stats['by_account'][account]['autosvar'] += 1
    elif email_type == 'bounce':
        stats['total_bounces'] += 1
        stats['by_account'][account]['bounces'] += 1
    elif email_type == 'marketing':
        stats['total_marketing'] += 1
        stats['by_account'][account]['marketing'] += 1

    stats['total_processed'] += 1

    # Track detection reasons
    if reason:
        if isinstance(stats['by_reason'], dict):
            stats['by_reason'][reason] = stats['by_reason'].get(reason, 0) + 1
        else:
            stats['by_reason'][reason] += 1

    # Track daily stats
    if today not in stats['by_date']:
        stats['by_date'][today] = {'autosvar': 0, 'bounces': 0, 'marketing': 0}
    if 'marketing' not in stats['by_date'][today]:
        stats['by_date'][today]['marketing'] = 0

    if email_type == 'autosvar':
        stats['by_date'][today]['autosvar'] += 1
    elif email_type == 'bounce':
        stats['by_date'][today]['bounces'] += 1
    elif email_type == 'marketing':
        stats['by_date'][today]['marketing'] += 1


def show_stats():
    """Display detection statistics."""
    stats = load_stats()

    print("=== AUTOSVAR FILTER - STATISTICS ===")
    print()

    if stats['last_run']:
        print(f"Last run: {stats['last_run']}")
    print(f"Total emails processed: {stats['total_processed']}")
    print(f"Total autoreplies detected: {stats['total_autosvar']}")
    print(f"Total bounces detected: {stats['total_bounces']}")
    print(f"Total marketing detected: {stats.get('total_marketing', 0)}")
    print()

    # By account
    if stats['by_account']:
        print("=== BY ACCOUNT ===")
        for account, counts in sorted(stats['by_account'].items()):
            mkt = counts.get('marketing', 0)
            total = counts['autosvar'] + counts['bounces'] + mkt
            if total > 0:
                print(f"  {account[:30]:30} | Auto: {counts['autosvar']:3} | Bounce: {counts['bounces']:3} | Mkt: {mkt:3}")
        print()

    # By detection reason (top 15)
    if stats['by_reason']:
        print("=== TOP DETECTION REASONS ===")
        sorted_reasons = sorted(stats['by_reason'].items(), key=lambda x: x[1], reverse=True)[:15]
        for reason, count in sorted_reasons:
            print(f"  {count:4} | {reason[:55]}")
        print()

    # Recent daily stats (last 7 days)
    if stats['by_date']:
        print("=== LAST 7 DAYS ===")
        sorted_dates = sorted(stats['by_date'].keys(), reverse=True)[:7]
        for date in sorted_dates:
            day_stats = stats['by_date'][date]
            mkt = day_stats.get('marketing', 0)
            print(f"  {date} | Auto: {day_stats['autosvar']:3} | Bounce: {day_stats['bounces']:3} | Mkt: {mkt:3}")
        print()


def get_folder_name(folder_name, account_type):
    """Get the correct folder name for the account type."""
    if account_type == 'a2':
        return f"INBOX.{folder_name}"
    return folder_name


def ensure_folder_exists(imap, folder_name, account_type):
    """Create folder if it doesn't exist."""
    # Get the correct folder name for this account type
    full_folder_name = get_folder_name(folder_name, account_type)

    # Check if folder exists
    status, folders = imap.list()
    folder_exists = False

    for f in folders:
        if f:
            # Parse folder name from IMAP response
            try:
                decoded = f.decode()
                # Check if our folder name appears in the listing
                if full_folder_name.upper() in decoded.upper():
                    folder_exists = True
                    break
            except:
                pass

    if not folder_exists:
        result = imap.create(full_folder_name)
        if result[0] == 'OK':
            print(f"    Created folder: {full_folder_name}")
        else:
            print(f"    Warning: Could not create folder {full_folder_name}: {result}")

    return full_folder_name


def process_account(email_addr, config, dry_run=False, include_bounces=True, include_marketing=True, stats=None):
    """Process a single email account."""
    password = os.getenv(config['password_env'])
    if not password:
        logger.warning(f"No password found for {email_addr}")
        print(f"  [SKIP] No password found for {email_addr}")
        return {'autosvar': 0, 'bounces': 0, 'marketing': 0, 'moved': 0}

    try:
        # Connect to IMAP
        imap = imaplib.IMAP4_SSL(config['server'], config['port'])
        imap.login(email_addr, password)

        # Select INBOX
        status, msgs = imap.select('INBOX')
        if status != 'OK':
            print(f"  [ERROR] Could not select INBOX: {msgs}")
            return {'autosvar': 0, 'bounces': 0, 'marketing': 0, 'moved': 0}

        total_messages = int(msgs[0])
        print(f"  INBOX: {total_messages} messages")

        if total_messages == 0:
            imap.logout()
            return {'autosvar': 0, 'bounces': 0, 'marketing': 0, 'moved': 0}

        # Ensure target folders exist and get correct folder names
        # Marketing emails are deleted, not moved to folder
        if not dry_run:
            autosvar_folder = ensure_folder_exists(imap, TARGET_FOLDER_AUTOSVAR, config['type'])
            if include_bounces:
                bounces_folder = ensure_folder_exists(imap, TARGET_FOLDER_BOUNCES, config['type'])
            else:
                bounces_folder = None
        else:
            autosvar_folder = get_folder_name(TARGET_FOLDER_AUTOSVAR, config['type'])
            bounces_folder = get_folder_name(TARGET_FOLDER_BOUNCES, config['type']) if include_bounces else None

        # Re-select INBOX after folder operations
        imap.select('INBOX')

        # Search all messages
        status, message_ids = imap.search(None, 'ALL')
        if status != 'OK':
            print(f"  [ERROR] Search failed: {message_ids}")
            imap.logout()
            return {'autosvar': 0, 'bounces': 0, 'marketing': 0, 'moved': 0}

        ids = message_ids[0].split()
        autosvar_count = 0
        bounce_count = 0
        marketing_count = 0
        moved_count = 0

        for msg_id in ids:
            try:
                # Fetch headers only (more efficient)
                status, data = imap.fetch(msg_id, '(RFC822.HEADER)')
                if status != 'OK' or not data or not data[0]:
                    continue

                raw_header = data[0][1] if isinstance(data[0], tuple) and len(data[0]) > 1 else None
                if not raw_header:
                    continue

                msg = email.message_from_bytes(raw_header)
                subject = decode_subject(msg)[:50]
                from_addr = msg.get('From', '')[:40]
            except Exception as e:
                continue

            # Check for bounce first
            is_bounce_email, bounce_reason = is_bounce(msg)
            if is_bounce_email and include_bounces:
                bounce_count += 1
                # Log the detection
                logger.info(f"BOUNCE | {email_addr} | {from_addr} | {subject} | {bounce_reason}")
                # Update stats
                if stats is not None:
                    update_stats(stats, email_addr, bounce_reason, 'bounce')
                if dry_run:
                    print(f"    [BOUNCE] {subject}")
                    print(f"             From: {from_addr}")
                    print(f"             Reason: {bounce_reason}")
                else:
                    result = imap.copy(msg_id, bounces_folder)
                    if result[0] == 'OK':
                        imap.store(msg_id, '+FLAGS', '\\Deleted')
                        moved_count += 1
                        print(f"    [MOVED->BOUNCES] {subject}")
                    else:
                        logger.error(f"Could not move bounce: {result}")
                        print(f"    [ERROR] Could not move bounce: {result}")
                continue

            # Check for marketing - DELETE these
            is_mkt, mkt_reason = is_marketing(msg)
            if is_mkt and include_marketing:
                marketing_count += 1
                logger.info(f"MARKETING | {email_addr} | {from_addr} | {subject} | {mkt_reason}")
                if stats is not None:
                    update_stats(stats, email_addr, mkt_reason, 'marketing')
                if dry_run:
                    print(f"    [MARKETING] {subject}")
                    print(f"                From: {from_addr}")
                    print(f"                Reason: {mkt_reason}")
                else:
                    # Try to unsubscribe first
                    http_url, mailto_url = extract_unsubscribe_link(msg)
                    unsub_result = None
                    if http_url or mailto_url:
                        unsub_result = auto_unsubscribe(http_url, mailto_url, from_addr, subject)

                    # Save to blocked senders list
                    save_blocked_sender(from_addr, subject, mkt_reason)

                    # Delete marketing emails directly (no copy to folder)
                    imap.store(msg_id, '+FLAGS', '\\Deleted')
                    moved_count += 1
                    if unsub_result and unsub_result.startswith('SUCCESS'):
                        print(f"    [UNSUBSCRIBED+DELETED] {subject}")
                    else:
                        print(f"    [DELETED] {subject}")
                continue

            # Check for autosvar
            is_auto, auto_reason = is_autosvar(msg)
            if is_auto:
                autosvar_count += 1
                # Log the detection
                logger.info(f"AUTOSVAR | {email_addr} | {from_addr} | {subject} | {auto_reason}")
                # Update stats
                if stats is not None:
                    update_stats(stats, email_addr, auto_reason, 'autosvar')
                if dry_run:
                    print(f"    [AUTOSVAR] {subject}")
                    print(f"               From: {from_addr}")
                    print(f"               Reason: {auto_reason}")
                else:
                    result = imap.copy(msg_id, autosvar_folder)
                    if result[0] == 'OK':
                        imap.store(msg_id, '+FLAGS', '\\Deleted')
                        moved_count += 1
                        print(f"    [MOVED->AUTOMATED] {subject}")
                    else:
                        logger.error(f"Could not move autosvar: {result}")
                        print(f"    [ERROR] Could not move autosvar: {result}")

        # Expunge deleted messages
        if not dry_run and moved_count > 0:
            imap.expunge()

        imap.logout()
        return {'autosvar': autosvar_count, 'bounces': bounce_count, 'marketing': marketing_count, 'moved': moved_count}

    except imaplib.IMAP4.error as e:
        logger.error(f"IMAP error for {email_addr}: {e}")
        print(f"  [IMAP ERROR] {e}")
        return {'autosvar': 0, 'bounces': 0, 'marketing': 0, 'moved': 0}
    except Exception as e:
        logger.error(f"Error processing {email_addr}: {e}")
        print(f"  [ERROR] {e}")
        return {'autosvar': 0, 'bounces': 0, 'marketing': 0, 'moved': 0}


def show_status():
    """Show status of all configured accounts."""
    print("=== AUTOSVAR FILTER - ACCOUNT STATUS ===")
    print()

    for email_addr, config in ACCOUNTS.items():
        password = os.getenv(config['password_env'])
        status = "OK" if password else "NO PASSWORD"

        if password:
            try:
                imap = imaplib.IMAP4_SSL(config['server'], config['port'])
                imap.login(email_addr, password)

                # Check INBOX
                imap.select('INBOX')
                _, msgs = imap.search(None, 'ALL')
                inbox_count = len(msgs[0].split()) if msgs[0] else 0

                # Check AUTOMATED folder
                auto_count = 0
                try:
                    imap.select(TARGET_FOLDER_AUTOSVAR)
                    _, msgs = imap.search(None, 'ALL')
                    auto_count = len(msgs[0].split()) if msgs[0] else 0
                except:
                    auto_count = "N/A"

                # Check BOUNCES folder
                bounce_count = 0
                try:
                    imap.select(TARGET_FOLDER_BOUNCES)
                    _, msgs = imap.search(None, 'ALL')
                    bounce_count = len(msgs[0].split()) if msgs[0] else 0
                except:
                    bounce_count = "N/A"

                imap.logout()
                status = f"INBOX: {inbox_count}, AUTOMATED: {auto_count}, BOUNCES: {bounce_count}"

            except Exception as e:
                status = f"ERROR: {e}"

        print(f"  {email_addr}")
        print(f"    Type: {config['type']}")
        print(f"    Status: {status}")
        print()


def main():
    parser = argparse.ArgumentParser(description='Filter autosvar, bounces, and marketing emails to separate folders')
    parser.add_argument('--account', choices=['gmail', 'a2', 'all'], default='all',
                        help='Which accounts to process')
    parser.add_argument('--dry-run', action='store_true',
                        help='Show what would be moved without moving')
    parser.add_argument('--status', action='store_true',
                        help='Show account status')
    parser.add_argument('--stats', action='store_true',
                        help='Show detection statistics')
    parser.add_argument('--email', type=str,
                        help='Process specific email address only')
    parser.add_argument('--no-bounces', action='store_true',
                        help='Skip bounce processing')
    parser.add_argument('--no-marketing', action='store_true',
                        help='Skip marketing email processing')
    args = parser.parse_args()

    if args.status:
        show_status()
        return

    if args.stats:
        show_stats()
        return

    # Load statistics for tracking
    stats = load_stats()

    logger.info(f"Starting autosvar filter - Mode: {'DRY RUN' if args.dry_run else 'LIVE'}")
    print("=== AUTOSVAR FILTER ===")
    print(f"Mode: {'DRY RUN' if args.dry_run else 'LIVE'}")
    print(f"Autosvar  -> {TARGET_FOLDER_AUTOSVAR}")
    if not args.no_bounces:
        print(f"Bounces   -> {TARGET_FOLDER_BOUNCES}")
    if not args.no_marketing:
        print(f"Marketing -> DELETE")
    print(f"Log file: {LOG_FILE}")
    print()

    total_autosvar = 0
    total_bounces = 0
    total_marketing = 0
    total_moved = 0

    for email_addr, config in ACCOUNTS.items():
        # Filter by account type
        if args.account != 'all' and config['type'] != args.account:
            continue

        # Filter by specific email
        if args.email and email_addr != args.email:
            continue

        print(f"Processing: {email_addr}")
        result = process_account(email_addr, config, args.dry_run, not args.no_bounces, not args.no_marketing, stats)
        total_autosvar += result['autosvar']
        total_bounces += result['bounces']
        total_marketing += result['marketing']
        total_moved += result['moved']

        found = result['autosvar'] + result['bounces'] + result['marketing']
        if found > 0:
            if result['autosvar'] > 0:
                print(f"  Autosvar: {result['autosvar']}")
            if result['bounces'] > 0:
                print(f"  Bounces: {result['bounces']}")
            if result['marketing'] > 0:
                print(f"  Marketing: {result['marketing']}")
            if not args.dry_run:
                print(f"  Total moved: {result['moved']}")
        else:
            print(f"  Nothing found")
        print()

    # Save statistics
    save_stats(stats)

    print("=== SUMMARY ===")
    print(f"Autosvar found: {total_autosvar}")
    print(f"Bounces found: {total_bounces}")
    print(f"Marketing found: {total_marketing}")
    print(f"Total: {total_autosvar + total_bounces + total_marketing}")
    if not args.dry_run:
        print(f"Total moved: {total_moved}")
    else:
        print("(Dry run - no emails moved)")

    logger.info(f"Completed - Autosvar: {total_autosvar}, Bounces: {total_bounces}, Marketing: {total_marketing}, Moved: {total_moved}")


if __name__ == '__main__':
    main()
