#!/usr/bin/env python3
"""
D3 Visualizer - Generate interactive D3.js charts from CSV data
Usage: python3 d3_visualizer.py <input.csv> [--type bar|pie|line] [--output chart.html]
"""
import sys
sys.path.insert(0, '/opt/ACTIVE/SCRAPERS/EUROPE/SCRIPTS/SHARED')
from skills_common import to_ascii, sanitize, FIELD_LIMITS

import os
import csv
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional
from collections import Counter

# ============================================================
# CHART TEMPLATES
# ============================================================

HTML_TEMPLATE = '''<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{title}</title>
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }}
        .container {{ max-width: 900px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        h1 {{ color: #333; }}
        .chart {{ margin: 20px 0; }}
        .bar {{ fill: #4472C4; }}
        .bar:hover {{ fill: #2c5aa0; }}
        .pie-slice {{ stroke: white; stroke-width: 2px; }}
        .axis text {{ font-size: 12px; }}
        .tooltip {{ position: absolute; background: #333; color: white; padding: 8px 12px; border-radius: 4px; font-size: 12px; pointer-events: none; }}
        .legend {{ font-size: 12px; }}
        .legend rect {{ stroke: #ccc; }}
        footer {{ margin-top: 30px; color: #666; font-size: 12px; text-align: center; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{title}</h1>
        <p>Data: {data_source} | Generated: {timestamp}</p>
        <div id="chart" class="chart"></div>
        <div id="legend"></div>
        <footer>Generated by d3_visualizer.py</footer>
    </div>
    <script>
        const data = {data_json};
        {chart_script}
    </script>
</body>
</html>'''

BAR_CHART_SCRIPT = '''
const margin = {top: 30, right: 30, bottom: 100, left: 60};
const width = 800 - margin.left - margin.right;
const height = 400 - margin.top - margin.bottom;

const svg = d3.select("#chart")
    .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
    .append("g")
    .attr("transform", `translate(${margin.left},${margin.top})`);

const x = d3.scaleBand()
    .range([0, width])
    .domain(data.map(d => d.label))
    .padding(0.2);

const y = d3.scaleLinear()
    .domain([0, d3.max(data, d => d.value) * 1.1])
    .range([height, 0]);

svg.append("g")
    .attr("transform", `translate(0,${height})`)
    .call(d3.axisBottom(x))
    .selectAll("text")
    .attr("transform", "rotate(-45)")
    .style("text-anchor", "end");

svg.append("g")
    .call(d3.axisLeft(y));

const tooltip = d3.select("body").append("div").attr("class", "tooltip").style("opacity", 0);

svg.selectAll(".bar")
    .data(data)
    .enter()
    .append("rect")
    .attr("class", "bar")
    .attr("x", d => x(d.label))
    .attr("y", d => y(d.value))
    .attr("width", x.bandwidth())
    .attr("height", d => height - y(d.value))
    .on("mouseover", function(event, d) {
        tooltip.transition().duration(200).style("opacity", .9);
        tooltip.html(`${d.label}: ${d.value}`)
            .style("left", (event.pageX + 10) + "px")
            .style("top", (event.pageY - 28) + "px");
    })
    .on("mouseout", function(d) {
        tooltip.transition().duration(500).style("opacity", 0);
    });
'''

PIE_CHART_SCRIPT = '''
const width = 500, height = 400, radius = Math.min(width, height) / 2 - 40;

const color = d3.scaleOrdinal()
    .domain(data.map(d => d.label))
    .range(d3.schemeCategory10);

const svg = d3.select("#chart")
    .append("svg")
    .attr("width", width)
    .attr("height", height)
    .append("g")
    .attr("transform", `translate(${width/2},${height/2})`);

const pie = d3.pie().value(d => d.value);
const arc = d3.arc().innerRadius(0).outerRadius(radius);
const labelArc = d3.arc().innerRadius(radius * 0.6).outerRadius(radius * 0.6);

const tooltip = d3.select("body").append("div").attr("class", "tooltip").style("opacity", 0);

svg.selectAll("path")
    .data(pie(data))
    .enter()
    .append("path")
    .attr("class", "pie-slice")
    .attr("d", arc)
    .attr("fill", d => color(d.data.label))
    .on("mouseover", function(event, d) {
        tooltip.transition().duration(200).style("opacity", .9);
        const pct = (d.data.value / d3.sum(data, x => x.value) * 100).toFixed(1);
        tooltip.html(`${d.data.label}: ${d.data.value} (${pct}%)`)
            .style("left", (event.pageX + 10) + "px")
            .style("top", (event.pageY - 28) + "px");
    })
    .on("mouseout", function(d) {
        tooltip.transition().duration(500).style("opacity", 0);
    });

// Legend
const legend = d3.select("#legend").append("svg").attr("width", 300).attr("height", data.length * 25);
const legendItems = legend.selectAll(".legend-item").data(data).enter().append("g")
    .attr("transform", (d, i) => `translate(0, ${i * 22})`);
legendItems.append("rect").attr("width", 18).attr("height", 18).attr("fill", d => color(d.label));
legendItems.append("text").attr("x", 24).attr("y", 14).text(d => `${d.label}: ${d.value}`);
'''

LINE_CHART_SCRIPT = '''
const margin = {top: 30, right: 30, bottom: 50, left: 60};
const width = 800 - margin.left - margin.right;
const height = 400 - margin.top - margin.bottom;

const svg = d3.select("#chart")
    .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
    .append("g")
    .attr("transform", `translate(${margin.left},${margin.top})`);

const x = d3.scalePoint()
    .range([0, width])
    .domain(data.map(d => d.label));

const y = d3.scaleLinear()
    .domain([0, d3.max(data, d => d.value) * 1.1])
    .range([height, 0]);

svg.append("g")
    .attr("transform", `translate(0,${height})`)
    .call(d3.axisBottom(x));

svg.append("g")
    .call(d3.axisLeft(y));

const line = d3.line()
    .x(d => x(d.label))
    .y(d => y(d.value));

svg.append("path")
    .datum(data)
    .attr("fill", "none")
    .attr("stroke", "#4472C4")
    .attr("stroke-width", 2)
    .attr("d", line);

svg.selectAll(".dot")
    .data(data)
    .enter()
    .append("circle")
    .attr("class", "dot")
    .attr("cx", d => x(d.label))
    .attr("cy", d => y(d.value))
    .attr("r", 5)
    .attr("fill", "#4472C4");
'''

# ============================================================
# DATA PROCESSING
# ============================================================

def read_csv_data(filepath: str) -> tuple:
    """Read CSV and return headers and rows"""
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        reader = csv.DictReader(f)
        headers = reader.fieldnames or []
        rows = list(reader)
    return headers, rows

def detect_chart_type(headers: List[str], rows: List[Dict]) -> str:
    """Auto-detect best chart type"""
    if not rows:
        return 'bar'

    # Check for date columns (line chart)
    for h in headers:
        if 'date' in h.lower() or 'time' in h.lower():
            return 'line'

    # Check for categorical data with few unique values (pie chart)
    for h in headers:
        values = [r.get(h, '') for r in rows[:100]]
        unique = len(set(values))
        if 3 <= unique <= 10:
            return 'pie'

    return 'bar'

def prepare_chart_data(rows: List[Dict], label_col: str, value_col: str = None) -> List[Dict]:
    """Prepare data for charting"""
    data = []

    if value_col:
        # Use specified value column
        for row in rows[:50]:
            label = str(row.get(label_col, ''))[:30]
            try:
                value = float(str(row.get(value_col, 0)).replace(',', ''))
            except Exception:
                value = 0
            if label and value:
                data.append({'label': label, 'value': value})
    else:
        # Count occurrences
        counter = Counter()
        for row in rows:
            label = str(row.get(label_col, ''))[:30]
            if label:
                counter[label] += 1
        data = [{'label': k, 'value': v} for k, v in counter.most_common(20)]

    return data

def find_columns(headers: List[str]) -> tuple:
    """Find label and value columns"""
    label_col = value_col = None

    # Find label column
    for h in headers:
        hl = h.lower()
        if any(x in hl for x in ['name', 'label', 'category', 'country', 'type', 'domain', 'email']):
            label_col = h
            break
    if not label_col:
        label_col = headers[0]

    # Find value column
    for h in headers:
        hl = h.lower()
        if any(x in hl for x in ['count', 'value', 'amount', 'total', 'score', 'num']):
            value_col = h
            break

    return label_col, value_col

# ============================================================
# CHART GENERATION
# ============================================================

def generate_chart(
    data: List[Dict],
    chart_type: str,
    title: str,
    data_source: str,
    output_path: str,
):
    """Generate HTML chart"""
    scripts = {
        'bar': BAR_CHART_SCRIPT,
        'pie': PIE_CHART_SCRIPT,
        'line': LINE_CHART_SCRIPT,
    }

    html = HTML_TEMPLATE.format(
        title=title,
        data_source=data_source,
        timestamp=datetime.now().strftime('%Y-%m-%d %H:%M'),
        data_json=json.dumps(data),
        chart_script=scripts.get(chart_type, BAR_CHART_SCRIPT),
    )

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)

    return output_path

# ============================================================
# MAIN
# ============================================================

def main():
    args = sys.argv[1:]

    if not args or '-h' in args or '--help' in args:
        print(f"""
{'='*60}
D3 VISUALIZER
{'='*60}

Usage: d3_visualizer.py <input.csv> [options]

Options:
  --type TYPE       Chart type: bar, pie, line (default: auto)
  --output FILE     Output HTML file (default: chart.html)
  --title TEXT      Chart title
  --label COL       Column to use for labels
  --value COL       Column to use for values (if numeric)

Examples:
  d3_visualizer.py contacts.csv --type pie
  d3_visualizer.py sales.csv --type bar --title "Sales by Region"
  d3_visualizer.py trends.csv --type line --output trends.html
  d3_visualizer.py data.csv --label country --value count
""")
        return

    # Parse arguments
    input_file = None
    chart_type = None
    output_file = 'chart.html'
    title = None
    label_col = value_col = None

    i = 0
    while i < len(args):
        arg = args[i]
        if arg == '--type' and i + 1 < len(args):
            chart_type = args[i + 1]
            i += 2
        elif arg == '--output' and i + 1 < len(args):
            output_file = args[i + 1]
            i += 2
        elif arg == '--title' and i + 1 < len(args):
            title = args[i + 1]
            i += 2
        elif arg == '--label' and i + 1 < len(args):
            label_col = args[i + 1]
            i += 2
        elif arg == '--value' and i + 1 < len(args):
            value_col = args[i + 1]
            i += 2
        elif arg.endswith('.csv') and os.path.exists(arg):
            input_file = arg
            i += 1
        else:
            i += 1

    if not input_file:
        print("Error: No CSV file specified")
        return

    print(f"\n{'='*60}")
    print("D3 VISUALIZER")
    print(f"{'='*60}\n")

    # Read data
    headers, rows = read_csv_data(input_file)
    print(f"Input: {Path(input_file).name}")
    print(f"Rows: {len(rows)}, Columns: {len(headers)}")

    # Auto-detect columns if not specified
    if not label_col:
        label_col, auto_value = find_columns(headers)
        if not value_col:
            value_col = auto_value
    print(f"Label column: {label_col}")
    print(f"Value column: {value_col or '(count occurrences)'}")

    # Auto-detect chart type
    if not chart_type:
        chart_type = detect_chart_type(headers, rows)
    print(f"Chart type: {chart_type}")

    # Prepare data
    data = prepare_chart_data(rows, label_col, value_col)
    print(f"Data points: {len(data)}")

    if not data:
        print("Error: No data to chart")
        return

    # Generate title
    if not title:
        title = f"{Path(input_file).stem} - {chart_type.title()} Chart"

    # Generate chart
    generate_chart(data, chart_type, title, Path(input_file).name, output_file)

    print(f"\nSaved to: {output_file}")
    print(f"Open in browser to view interactive chart")
    print(f"\n{'='*60}\n")

if __name__ == '__main__':
    main()
