#!/usr/bin/env python3
"""
Email Sorter & Autoresponder

Connects to all 30 email accounts (19 A2 Hosting, 9 Gmail, 2 Yahoo) via IMAP and:
1. Creates APPLICATIONS_RECEIVED and AUTOREPLY IMAP folders
2. Sorts INBOX emails:
   - Autoreplies/bounces/out-of-office -> AUTOREPLY folder
   - Job applications/CVs/form submissions -> APPLICATIONS_RECEIVED folder
3. Sets up autoresponders:
   - A2 Hosting: cPanel UAPI autoresponders (server-side)
   - Gmail/Yahoo: SMTP auto-reply to new senders (tracked in replied.json)

Usage:
    python email_sorter.py                              # Sort all + autoresponders
    python email_sorter.py --sort-only                  # Only sort emails
    python email_sorter.py --setup-only                 # Only folders + autoresponders
    python email_sorter.py --dry-run                    # Preview without changes
    python email_sorter.py --status                     # Show current state
    python email_sorter.py --days 30                    # Process last 30 days (default: 7)
    python email_sorter.py --account office@factoryjobs.eu  # Single account
    python email_sorter.py --no-reply                   # Skip SMTP auto-replies
"""

import imaplib
import smtplib
import ssl
import email
import email.header
import email.utils
import re
import json
import urllib.request
import urllib.parse
import argparse
import sys
import os
import time
from datetime import datetime, timedelta

try:
    import fcntl  # POSIX only; production runs on raspibig (Linux)
except ImportError:  # Windows dev fallback — no-op locking
    fcntl = None
from email.mime.text import MIMEText


# =============================================================================
# CONFIGURATION
# =============================================================================

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPLIED_JSON = os.path.join(SCRIPT_DIR, "replied.json")

TARGET_FOLDERS = ["APPLICATIONS_RECEIVED", "AUTOREPLY"]

# Auto-reply template (used for both cPanel and SMTP)
AUTOREPLY_SUBJECT = "Thank you for your message"
AUTOREPLY_BODY = """Thank you for contacting us.

We have received your message and will review it as soon as possible.

If you sent a CV or job application, our recruitment team will get back to you within 3-5 business days.

For urgent matters, please visit our website for more information.

Best regards,
The Recruitment Team"""

AUTOREPLY_INTERVAL_HOURS = 24

# =============================================================================
# ACCOUNTS
# =============================================================================

# Credentials moved to /opt/ACTIVE/EMAIL/.env (2026-04-28 security fix)
import os, dotenv
dotenv.load_dotenv("/opt/ACTIVE/EMAIL/.env")

def load_accounts():
    """Load accounts from env vars (EMAIL_SORTER_ACCOUNTS_JSON or defaults)."""
    import json
    accounts_json = os.environ.get("EMAIL_SORTER_ACCOUNTS_JSON", "")
    if accounts_json:
        return json.loads(accounts_json)
    log_error("EMAIL_SORTER_ACCOUNTS_JSON not set in /opt/ACTIVE/EMAIL/.env")
    return []

A2_ACCOUNTS = load_accounts()  # Will be populated from .env at runtime
GMAIL_ACCOUNTS = []
YAHOO_ACCOUNTS = []

# cPanel API
CPANEL_HOST = "nl1-cl8-ats1.a2hosting.com"
CPANEL_PORT = 2083
CPANEL_USER = "loaiidil"
CPANEL_TOKEN = None

# =============================================================================
# DETECTION PATTERNS
# =============================================================================

# --- Autoreply detection ---

AUTOREPLY_HEADERS = [
    "X-Autoreply",
    "X-Autorespond",
    "X-Autogenerated",
    "X-AutoReply-From",
]

AUTOREPLY_SENDER_PATTERNS = [
    "noreply-autoreply@", "auto-reply@", "autoreply@", "vacation@",
    "ooo@", "out-of-office@", "autoresponder@", "do-not-reply@",
    "donotreply@", "mailer-daemon@", "postmaster@", "mail-daemon@",
]

AUTOREPLY_SUBJECT_RE = re.compile(
    r"autosvar|automatiskt svar|auto[\-\s]?reply|automatic reply|"
    r"out of office|abwesenheitsnotiz|automatische antwort|"
    r"r[ée]ponse automatique|risposta automatica|respuesta autom[aá]tica|"
    r"automatisch antwoord|automaattinen vastaus|automatisk svar|"
    r"fr[åa]nvaro|afwezigheidsbericht|vacation|away from .{0,20}(office|desk)|"
    r"automated response|auto response",
    re.IGNORECASE
)

BOUNCE_SUBJECT_RE = re.compile(
    r"delivery (status|failure|notification)|undeliverable|undelivered mail|"
    r"returned (to sender|mail)|mail delivery (failed|system)|"
    r"failure notice|non[\-\s]?delivery|could not be delivered|"
    r"delivery has failed",
    re.IGNORECASE
)

BOUNCE_SENDERS = ["mailer-daemon", "postmaster", "mail-daemon"]

# --- Application detection ---

APPLICATION_SENDER_DOMAINS = [
    "buildjobs.eu", "factoryjobs.eu", "warehouseworkers.eu", "interjob.ro",
    "mivromania.info", "mivromania.online", "careworkers.eu", "cifn.info",
    "nepalezi.com", "expatsinromania.org", "horecaworkers.eu", "meatworkers.eu",
    "electricjobs.eu", "mechanicjobs.eu", "farmworkers.eu",
    "horecaworkers2026.eu", "horecaworkers2026.com", "horecaworkers2026.online",
    "internaltransfers.eu",
    "formspree.io",
]

APPLICATION_SUBJECT_RE = re.compile(
    r"new submission|form submission|contact form|formspree|"
    r"new application|job application|cv attached|resume attached|"
    r"candidatura|aplicare pentru|looking for (a )?(job|work)|"
    r"caut lucru|seeking employment|application for|apply(ing)? for",
    re.IGNORECASE
)

APPLICATION_BODY_RE = re.compile(
    r"attached my cv|attached cv|my resume|job seeker|"
    r"available for work|available immediately|willing to relocate|"
    r"years of experience|work permit|looking for (a )?(job|work)|"
    r"please find (my |attached )",
    re.IGNORECASE
)

APPLICATION_ATTACHMENT_RE = re.compile(
    r"(cv|resume|lebenslauf|curriculum)", re.IGNORECASE
)

APPLICATION_ATTACHMENT_EXTS = {".pdf", ".doc", ".docx"}

# Senders we should never auto-reply to
NO_REPLY_SENDERS_RE = re.compile(
    r"noreply|no[\-\.]reply|do[\-\.]not[\-\.]reply|mailer[\-\.]daemon|"
    r"postmaster|bounce|automated|notification|alert",
    re.IGNORECASE
)


# =============================================================================
# IMAP HELPERS
# =============================================================================

def make_ssl_context():
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    return ctx


def imap_connect(server, port, email_addr, password):
    """Connect to IMAP and login. Returns (imap, None) or (None, error_str)."""
    try:
        imap = imaplib.IMAP4_SSL(server, port, ssl_context=make_ssl_context())
        imap.login(email_addr, password)
        return imap, None
    except Exception as e:
        return None, str(e)


def imap_list_folders(imap):
    """List all folder names."""
    status, data = imap.list()
    if status != "OK":
        return []
    folders = []
    for item in data:
        try:
            decoded = item.decode() if isinstance(item, bytes) else str(item)
            # Parse: (\flags) "delimiter" "name" or (\flags) "delimiter" name
            match = re.search(r'"([^"]*)"$|(\S+)$', decoded)
            if match:
                name = match.group(1) if match.group(1) is not None else match.group(2)
                folders.append(name)
        except:
            pass
    return folders


def imap_ensure_folders(imap, provider="a2"):
    """Create target folders if they don't exist. Returns list of created folders."""
    existing = imap_list_folders(imap)
    existing_lower = [f.lower() for f in existing]
    created = []

    for folder in TARGET_FOLDERS:
        # Check plain name
        if folder.lower() in existing_lower:
            continue
        # For A2, also check INBOX.prefix
        if provider == "a2" and f"inbox.{folder.lower()}" in existing_lower:
            continue

        # Try creating
        names_to_try = [folder]
        if provider == "a2":
            names_to_try.append(f"INBOX.{folder}")

        for name in names_to_try:
            try:
                status, _ = imap.create(name)
                if status == "OK":
                    created.append(name)
                    break
            except Exception as e:
                err = str(e).lower()
                if "already exists" in err or "alreadyexists" in err:
                    break
                continue

    return created


def imap_get_folder_name(imap, target, provider="a2"):
    """Find the actual folder name for a target (handles INBOX. prefix)."""
    existing = imap_list_folders(imap)
    for f in existing:
        if f.lower() == target.lower():
            return f
        if f.lower() == f"inbox.{target.lower()}":
            return f
    return target


def imap_move_email(imap, uid, dest_folder):
    """Move email by UID: COPY + DELETE. Returns True on success."""
    try:
        status, _ = imap.uid("COPY", uid, dest_folder)
        if status == "OK":
            imap.uid("STORE", uid, "+FLAGS", "\\Deleted")
            return True
        return False
    except:
        return False


# =============================================================================
# EMAIL CLASSIFICATION
# =============================================================================

def decode_header_value(raw):
    """Decode an email header value to string."""
    if raw is None:
        return ""
    parts = email.header.decode_header(raw)
    decoded = []
    for part, charset in parts:
        if isinstance(part, bytes):
            decoded.append(part.decode(charset or "utf-8", errors="replace"))
        else:
            decoded.append(str(part))
    return " ".join(decoded)


def get_sender_email(msg):
    """Extract sender email address from From header."""
    from_header = decode_header_value(msg.get("From", ""))
    # Try to extract email from "Name <email>" or just "email"
    match = re.search(r'<([^>]+)>', from_header)
    if match:
        return match.group(1).lower().strip()
    # Fallback: might just be the email
    if "@" in from_header:
        return from_header.strip().lower()
    return from_header.lower().strip()


def is_autoreply(msg):
    """Check if message is an auto-reply, out-of-office, or bounce."""
    # Check auto-reply headers
    for header in AUTOREPLY_HEADERS:
        if msg.get(header):
            return True

    # Check Auto-Submitted (RFC 3834)
    auto_submitted = (msg.get("Auto-Submitted") or "").lower().strip()
    if auto_submitted and auto_submitted != "no":
        return True

    # Check Precedence header
    precedence = (msg.get("Precedence") or "").lower().strip()
    if precedence in ("auto_reply", "autoreply", "auto-reply", "bulk", "junk"):
        return True

    # Check sender patterns
    sender = get_sender_email(msg)
    for pattern in AUTOREPLY_SENDER_PATTERNS:
        if pattern in sender:
            return True

    # Check if sender is bounce address
    sender_local = sender.split("@")[0] if "@" in sender else sender
    if sender_local in BOUNCE_SENDERS:
        return True

    # Check subject
    subject = decode_header_value(msg.get("Subject", ""))
    if AUTOREPLY_SUBJECT_RE.search(subject):
        return True
    if BOUNCE_SUBJECT_RE.search(subject):
        return True

    return False


def is_application(msg, body_text=""):
    """Check if message is a job application."""
    sender = get_sender_email(msg)
    subject = decode_header_value(msg.get("Subject", ""))

    # Check sender domain
    if "@" in sender:
        domain = sender.split("@")[1]
        if domain in APPLICATION_SENDER_DOMAINS:
            return True

    # Check subject
    if APPLICATION_SUBJECT_RE.search(subject):
        return True

    # Check body keywords
    if body_text and APPLICATION_BODY_RE.search(body_text):
        return True

    # Check attachment filenames
    content_type = msg.get("Content-Type", "")
    content_disp = msg.get("Content-Disposition", "")
    combined = f"{content_type} {content_disp}".lower()

    if APPLICATION_ATTACHMENT_RE.search(combined):
        return True

    for ext in APPLICATION_ATTACHMENT_EXTS:
        if ext in combined:
            return True

    return False


def classify_email(msg, body_text=""):
    """Classify email. Returns 'autoreply', 'application', or None."""
    if is_autoreply(msg):
        return "autoreply"
    if is_application(msg, body_text):
        return "application"
    return None


# =============================================================================
# EMAIL SORTING
# =============================================================================

def get_body_preview(msg_data):
    """Extract first ~2000 chars of body text from IMAP FETCH result."""
    try:
        msg = email.message_from_bytes(msg_data)
        if msg.is_multipart():
            for part in msg.walk():
                ct = part.get_content_type()
                if ct == "text/plain":
                    payload = part.get_payload(decode=True)
                    if payload:
                        return payload.decode(errors="replace")[:2000]
                elif ct == "text/html":
                    payload = part.get_payload(decode=True)
                    if payload:
                        text = re.sub(r'<[^>]+>', ' ', payload.decode(errors="replace"))
                        return text[:2000]
        else:
            payload = msg.get_payload(decode=True)
            if payload:
                return payload.decode(errors="replace")[:2000]
    except:
        pass
    return ""


def get_attachment_info(msg_data):
    """Get attachment filenames from BODYSTRUCTURE or full message."""
    filenames = []
    try:
        msg = email.message_from_bytes(msg_data)
        if msg.is_multipart():
            for part in msg.walk():
                fn = part.get_filename()
                if fn:
                    filenames.append(decode_header_value(fn).lower())
    except:
        pass
    return filenames


def sort_account(imap, account_email, provider="a2", days=7, dry_run=False):
    """Sort emails in one account's INBOX. Returns stats dict."""
    stats = {"autoreply": 0, "application": 0, "skipped": 0, "errors": 0}

    # Get actual folder names
    autoreply_folder = imap_get_folder_name(imap, "AUTOREPLY", provider)
    applications_folder = imap_get_folder_name(imap, "APPLICATIONS_RECEIVED", provider)

    # Select INBOX
    try:
        status, data = imap.select("INBOX")
        if status != "OK":
            print(f"    Cannot select INBOX: {data}")
            return stats
    except Exception as e:
        print(f"    Cannot select INBOX: {e}")
        return stats

    # Search for emails within date range
    since_date = (datetime.now() - timedelta(days=days)).strftime("%d-%b-%Y")
    try:
        status, data = imap.uid("SEARCH", None, f'(SINCE "{since_date}")')
        if status != "OK" or not data[0]:
            print(f"    No emails found in last {days} days")
            return stats
    except Exception as e:
        print(f"    Search error: {e}")
        return stats

    uids = data[0].split()
    print(f"    Found {len(uids)} emails in last {days} days")

    for uid in uids:
        uid_str = uid.decode() if isinstance(uid, bytes) else str(uid)

        try:
            # Fetch headers first (efficient)
            status, header_data = imap.uid("FETCH", uid, "(BODY.PEEK[HEADER])")
            if status != "OK" or not header_data or not header_data[0]:
                stats["errors"] += 1
                continue

            raw_headers = header_data[0][1] if isinstance(header_data[0], tuple) else header_data[0]
            if isinstance(raw_headers, bytes):
                msg = email.message_from_bytes(raw_headers)
            else:
                stats["errors"] += 1
                continue

            sender = get_sender_email(msg)
            subject = decode_header_value(msg.get("Subject", ""))[:80]

            # Check if autoreply first (headers only)
            if is_autoreply(msg):
                classification = "autoreply"
            else:
                # Need body for application detection
                body_text = ""
                attachment_names = []

                # Fetch body structure to check attachments
                try:
                    status2, body_data = imap.uid("FETCH", uid, "(BODY.PEEK[]<0.8000>)")
                    if status2 == "OK" and body_data and body_data[0]:
                        raw_body = body_data[0][1] if isinstance(body_data[0], tuple) else body_data[0]
                        if isinstance(raw_body, bytes):
                            body_text = get_body_preview(raw_body)
                            attachment_names = get_attachment_info(raw_body)
                except:
                    pass

                # Build a fake content header with attachment info for is_application
                if attachment_names:
                    for fn in attachment_names:
                        msg["X-Attachment-Names"] = fn

                if is_application(msg, body_text):
                    classification = "application"
                else:
                    classification = None

            if classification is None:
                stats["skipped"] += 1
                continue

            dest = autoreply_folder if classification == "autoreply" else applications_folder
            label = "AUTOREPLY" if classification == "autoreply" else "APPLICATION"

            if dry_run:
                print(f"    [DRY] {label}: {sender} | {subject}")
                stats[classification] += 1
            else:
                if imap_move_email(imap, uid, dest):
                    print(f"    >> {label}: {sender} | {subject}")
                    stats[classification] += 1
                else:
                    print(f"    FAIL moving {uid_str} to {dest}")
                    stats["errors"] += 1

        except Exception as e:
            print(f"    Error on UID {uid_str}: {e}")
            stats["errors"] += 1

    # Expunge deleted messages
    if not dry_run and (stats["autoreply"] > 0 or stats["application"] > 0):
        try:
            imap.expunge()
        except:
            pass

    return stats


# =============================================================================
# SMTP AUTO-REPLY (Gmail + Yahoo)
# =============================================================================

def load_replied():
    """Load reply tracker from replied.json (shared lock for concurrent reads)."""
    try:
        f = open(REPLIED_JSON, "r")
    except FileNotFoundError:
        return {}
    try:
        if fcntl is not None:
            fcntl.flock(f.fileno(), fcntl.LOCK_SH)
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return {}
    finally:
        if fcntl is not None:
            try:
                fcntl.flock(f.fileno(), fcntl.LOCK_UN)
            except OSError:
                pass
        f.close()


def save_replied(data):
    """Save reply tracker to replied.json (exclusive lock prevents concurrent overwrite)."""
    f = open(REPLIED_JSON, "w")
    try:
        if fcntl is not None:
            fcntl.flock(f.fileno(), fcntl.LOCK_EX)
        json.dump(data, f, indent=2)
        f.flush()
        os.fsync(f.fileno())
    finally:
        if fcntl is not None:
            try:
                fcntl.flock(f.fileno(), fcntl.LOCK_UN)
            except OSError:
                pass
        f.close()


def clean_replied(data, max_age_days=30):
    """Remove entries older than max_age_days."""
    cutoff = (datetime.now() - timedelta(days=max_age_days)).isoformat()
    cleaned = {}
    for account, senders in data.items():
        cleaned[account] = {
            s: ts for s, ts in senders.items() if ts > cutoff
        }
    return cleaned


def should_reply(replied_data, account_email, sender_email):
    """Check if we should send an auto-reply to this sender."""
    # Never reply to noreply/automated senders
    if NO_REPLY_SENDERS_RE.search(sender_email):
        return False

    # Never reply to our own accounts
    our_emails = set()
    for acc in A2_ACCOUNTS + GMAIL_ACCOUNTS + YAHOO_ACCOUNTS:
        our_emails.add(acc["email"].lower())
    if sender_email.lower() in our_emails:
        return False

    # Check interval
    account_data = replied_data.get(account_email, {})
    last_reply = account_data.get(sender_email.lower())
    if last_reply:
        try:
            last_dt = datetime.fromisoformat(last_reply)
            if datetime.now() - last_dt < timedelta(hours=AUTOREPLY_INTERVAL_HOURS):
                return False
        except:
            pass

    return True


def send_smtp_reply(smtp_server, smtp_port, from_email, password, to_email, original_subject):
    """Send auto-reply via SMTP. Returns True on success."""
    try:
        reply_subject = f"Re: {original_subject}" if original_subject else AUTOREPLY_SUBJECT

        msg = MIMEText(AUTOREPLY_BODY)
        msg["From"] = from_email
        msg["To"] = to_email
        msg["Subject"] = reply_subject
        msg["Auto-Submitted"] = "auto-replied"
        msg["X-Autoreply"] = "yes"
        msg["Precedence"] = "auto_reply"

        with smtplib.SMTP(smtp_server, smtp_port, timeout=30) as server:
            server.starttls(context=make_ssl_context())
            server.login(from_email, password)
            server.sendmail(from_email, to_email, msg.as_string())

        return True
    except Exception as e:
        print(f"    SMTP error to {to_email}: {e}")
        return False


def send_autoreplies_for_account(imap, account_email, password, smtp_server, smtp_port,
                                  days=7, dry_run=False):
    """Scan INBOX for emails that need auto-replies and send them."""
    replied_data = load_replied()
    stats = {"sent": 0, "skipped": 0, "errors": 0}

    try:
        imap.select("INBOX")
        since_date = (datetime.now() - timedelta(days=days)).strftime("%d-%b-%Y")
        status, data = imap.uid("SEARCH", None, f'(SINCE "{since_date}")')
        if status != "OK" or not data[0]:
            return stats
    except:
        return stats

    uids = data[0].split()

    for uid in uids:
        try:
            status, header_data = imap.uid("FETCH", uid, "(BODY.PEEK[HEADER])")
            if status != "OK" or not header_data or not header_data[0]:
                continue

            raw = header_data[0][1] if isinstance(header_data[0], tuple) else header_data[0]
            if not isinstance(raw, bytes):
                continue

            msg = email.message_from_bytes(raw)
            sender = get_sender_email(msg)
            subject = decode_header_value(msg.get("Subject", ""))

            # Don't reply to autoreplies or bounces
            if is_autoreply(msg):
                stats["skipped"] += 1
                continue

            if not should_reply(replied_data, account_email, sender):
                stats["skipped"] += 1
                continue

            if dry_run:
                print(f"    [DRY] Would reply to: {sender} | {subject[:60]}")
                stats["sent"] += 1
            else:
                if send_smtp_reply(smtp_server, smtp_port, account_email, password, sender, subject):
                    print(f"    Replied to: {sender}")
                    stats["sent"] += 1
                    # Track the reply
                    if account_email not in replied_data:
                        replied_data[account_email] = {}
                    replied_data[account_email][sender.lower()] = datetime.now().isoformat()
                else:
                    stats["errors"] += 1

        except Exception as e:
            stats["errors"] += 1

    if not dry_run and stats["sent"] > 0:
        replied_data = clean_replied(replied_data)
        save_replied(replied_data)

    return stats


# =============================================================================
# CPANEL AUTORESPONDERS (A2 HOSTING)
# =============================================================================

def load_cpanel_token():
    global CPANEL_TOKEN
    token = os.environ.get("A2_CPANEL_TOKEN")
    if token:
        CPANEL_TOKEN = token
        return True
    for path in [
        os.path.expanduser("~/.a2hosting.env"),
        "D:/MEMORY/.a2hosting.env",
        "D:/MEMORY/A2_SITE_DEPLOYER/.env",
    ]:
        try:
            with open(path) as f:
                for line in f:
                    line = line.strip()
                    if line.startswith("A2_CPANEL_TOKEN="):
                        CPANEL_TOKEN = line.split("=", 1)[1].strip().strip("\"'")
                        return True
        except FileNotFoundError:
            continue
    return False


def cpanel_api(module, function, params=None):
    if not CPANEL_TOKEN:
        return {"status": 0, "errors": ["No cPanel token"]}
    url = f"https://{CPANEL_HOST}:{CPANEL_PORT}/execute/{module}/{function}"
    if params:
        url += "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(url)
    req.add_header("Authorization", f"cpanel {CPANEL_USER}:{CPANEL_TOKEN}")
    try:
        with urllib.request.urlopen(req, context=make_ssl_context(), timeout=30) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        return {"status": 0, "errors": [f"HTTP {e.code}: {e.reason}"]}
    except Exception as e:
        return {"status": 0, "errors": [str(e)]}


def setup_cpanel_autoresponders(dry_run=False):
    """Set up cPanel autoresponders on all A2 domains."""
    print("\n--- cPanel Autoresponders (A2 Hosting) ---")
    if not load_cpanel_token():
        print("  No cPanel token found. Skipping.")
        print("  Set A2_CPANEL_TOKEN env var or create ~/.a2hosting.env")
        return

    # Get existing autoresponders
    result = cpanel_api("Email", "list_auto_responders")
    existing = set()
    if result.get("status") == 1:
        for r in result.get("data", []):
            existing.add(r.get("domain", ""))

    stats = {"created": 0, "skipped": 0, "failed": 0}

    for acc in A2_ACCOUNTS:
        domain = acc["domain"]
        if domain in existing:
            print(f"  SKIP {domain} (already configured)")
            stats["skipped"] += 1
            continue

        if dry_run:
            print(f"  [DRY] Would add autoresponder for office@{domain}")
            stats["created"] += 1
            continue

        params = {
            "email": "office",
            "domain": domain,
            "from": f"office@{domain}",
            "subject": AUTOREPLY_SUBJECT,
            "body": AUTOREPLY_BODY,
            "interval": AUTOREPLY_INTERVAL_HOURS,
            "is_html": 0,
            "start": 0,
            "stop": 0,
        }
        result = cpanel_api("Email", "add_auto_responder", params)
        if result.get("status") == 1:
            print(f"  OK office@{domain}")
            stats["created"] += 1
        else:
            print(f"  FAIL office@{domain}: {result.get('errors')}")
            stats["failed"] += 1
        time.sleep(0.3)

    print(f"  Created: {stats['created']} | Skipped: {stats['skipped']} | Failed: {stats['failed']}")


# =============================================================================
# ACCOUNT PROCESSING
# =============================================================================

def get_all_accounts():
    """Build unified account list with connection details."""
    accounts = []
    seen = set()

    for acc in A2_ACCOUNTS + GMAIL_ACCOUNTS + YAHOO_ACCOUNTS:
        addr = acc["email"]
        if addr in seen:
            continue
        seen.add(addr)

        pw = acc.get("password")
        if not pw:
            log_error(f"  SKIP {addr}: no password in config")
            continue

        domain = acc.get("domain", "")
        if "gmail.com" in addr:
            accounts.append({
                "email": addr, "password": pw,
                "imap_server": "imap.gmail.com", "imap_port": 993,
                "smtp_server": "smtp.gmail.com", "smtp_port": 587,
                "provider": "gmail", "domain": None,
            })
        elif "yahoo.com" in addr:
            accounts.append({
                "email": addr, "password": pw,
                "imap_server": "imap.mail.yahoo.com", "imap_port": 993,
                "smtp_server": "smtp.mail.yahoo.com", "smtp_port": 587,
                "provider": "yahoo", "domain": None,
            })
        elif domain:
            accounts.append({
                "email": addr, "password": pw,
                "imap_server": f"mail.{domain}", "imap_port": 993,
                "smtp_server": None, "smtp_port": None,
                "provider": "a2", "domain": domain,
            })

    return accounts


def process_account(acc, days=7, dry_run=False, sort=True, reply=True):
    """Process a single email account: create folders, sort, send replies."""
    email_addr = acc["email"]
    provider = acc["provider"]
    print(f"\n  [{provider.upper()}] {email_addr}")

    imap, err = imap_connect(acc["imap_server"], acc["imap_port"], email_addr, acc["password"])
    if err:
        print(f"    FAILED: {err}")
        return False

    try:
        # Create folders
        created = imap_ensure_folders(imap, provider)
        if created:
            print(f"    Created folders: {', '.join(created)}")

        # Sort emails
        if sort:
            stats = sort_account(imap, email_addr, provider, days, dry_run)
            print(f"    Sorted: {stats['autoreply']} autoreplies, {stats['application']} applications, "
                  f"{stats['skipped']} unchanged, {stats['errors']} errors")

        # Send SMTP auto-replies (Gmail + Yahoo only)
        if reply and acc["smtp_server"]:
            reply_stats = send_autoreplies_for_account(
                imap, email_addr, acc["password"],
                acc["smtp_server"], acc["smtp_port"],
                days, dry_run
            )
            if reply_stats["sent"] > 0 or reply_stats["errors"] > 0:
                print(f"    Replies: {reply_stats['sent']} sent, {reply_stats['skipped']} skipped, "
                      f"{reply_stats['errors']} errors")

        return True

    except Exception as e:
        print(f"    Error: {e}")
        return False

    finally:
        try:
            imap.logout()
        except:
            pass


# =============================================================================
# STATUS
# =============================================================================

def run_status():
    """Show current state of all accounts."""
    print("=" * 70)
    print("EMAIL STATUS")
    print("=" * 70)

    accounts = get_all_accounts()
    results = {"ok": 0, "fail": 0}

    for acc in accounts:
        provider = acc["provider"].upper()
        email_addr = acc["email"]

        imap, err = imap_connect(acc["imap_server"], acc["imap_port"], email_addr, acc["password"])
        if err:
            print(f"  [{provider}] {email_addr}: FAIL ({err})")
            results["fail"] += 1
            continue

        try:
            folders = imap_list_folders(imap)
            has_autoreply = any(f.lower() in ("autoreply", "inbox.autoreply") for f in folders)
            has_apps = any(f.lower() in ("applications_received", "inbox.applications_received") for f in folders)

            # Count INBOX emails
            imap.select("INBOX", readonly=True)
            status, data = imap.search(None, "ALL")
            inbox_count = len(data[0].split()) if status == "OK" and data[0] else 0

            status_parts = []
            status_parts.append(f"INBOX: {inbox_count}")
            status_parts.append(f"AUTOREPLY: {'yes' if has_autoreply else 'NO'}")
            status_parts.append(f"APPS: {'yes' if has_apps else 'NO'}")

            print(f"  [{provider}] {email_addr}: {' | '.join(status_parts)}")
            results["ok"] += 1
            imap.logout()
        except Exception as e:
            print(f"  [{provider}] {email_addr}: ERROR ({e})")
            results["fail"] += 1

    print(f"\nConnected: {results['ok']} | Failed: {results['fail']} | Total: {results['ok'] + results['fail']}")

    # cPanel autoresponders
    print("\n--- cPanel Autoresponders ---")
    if load_cpanel_token():
        result = cpanel_api("Email", "list_auto_responders")
        if result.get("status") == 1:
            responders = result.get("data", [])
            if responders:
                for r in responders:
                    print(f"  office@{r.get('domain', 'N/A')}: {r.get('subject', 'N/A')}")
            else:
                print("  None configured")
        else:
            print(f"  Error: {result.get('errors')}")
    else:
        print("  No cPanel token found")

    # Reply tracker
    print("\n--- Reply Tracker ---")
    replied = load_replied()
    total_tracked = sum(len(v) for v in replied.values())
    print(f"  Tracking {total_tracked} sender(s) across {len(replied)} account(s)")


# =============================================================================
# SCAN — LIST ALL EMAILS IN INBOX
# =============================================================================

def scan_account(imap, account_email, provider="a2", days=7):
    """List every email in INBOX with classification. Returns stats dict."""
    stats = {"total": 0, "autoreply": 0, "application": 0, "normal": 0, "errors": 0}

    try:
        status, data = imap.select("INBOX", readonly=True)
        if status != "OK":
            print(f"    Cannot select INBOX: {data}")
            return stats
    except Exception as e:
        print(f"    Cannot select INBOX: {e}")
        return stats

    since_date = (datetime.now() - timedelta(days=days)).strftime("%d-%b-%Y")
    try:
        status, data = imap.uid("SEARCH", None, f'(SINCE "{since_date}")')
        if status != "OK" or not data[0]:
            print(f"    No emails in last {days} days")
            return stats
    except Exception as e:
        print(f"    Search error: {e}")
        return stats

    uids = data[0].split()
    print(f"    {len(uids)} emails in last {days} days:")

    for uid in uids:
        try:
            status, header_data = imap.uid("FETCH", uid, "(BODY.PEEK[HEADER])")
            if status != "OK" or not header_data or not header_data[0]:
                stats["errors"] += 1
                continue

            raw = header_data[0][1] if isinstance(header_data[0], tuple) else header_data[0]
            if not isinstance(raw, bytes):
                stats["errors"] += 1
                continue

            msg = email.message_from_bytes(raw)
            sender = get_sender_email(msg)
            subject = decode_header_value(msg.get("Subject", ""))[:80]
            date_str = msg.get("Date", "")[:25]

            # Classify
            if is_autoreply(msg):
                tag = "AUTOREPLY"
                stats["autoreply"] += 1
            else:
                # Check body for application
                body_text = ""
                try:
                    s2, bd = imap.uid("FETCH", uid, "(BODY.PEEK[]<0.8000>)")
                    if s2 == "OK" and bd and bd[0]:
                        raw_body = bd[0][1] if isinstance(bd[0], tuple) else bd[0]
                        if isinstance(raw_body, bytes):
                            body_text = get_body_preview(raw_body)
                except:
                    pass

                if is_application(msg, body_text):
                    tag = "APPLICATION"
                    stats["application"] += 1
                else:
                    tag = "---"
                    stats["normal"] += 1

            stats["total"] += 1
            print(f"    [{tag:12s}] {date_str} | {sender:40s} | {subject}")

        except Exception as e:
            stats["errors"] += 1

    return stats


def run_scan(accounts, days=7):
    """Scan all accounts and list every email."""
    print("=" * 70)
    print(f"INBOX SCAN — {len(accounts)} accounts, last {days} days")
    print("=" * 70)

    totals = {"total": 0, "autoreply": 0, "application": 0, "normal": 0, "errors": 0}

    for acc in accounts:
        provider = acc["provider"]
        email_addr = acc["email"]
        print(f"\n  [{provider.upper()}] {email_addr}")

        imap, err = imap_connect(acc["imap_server"], acc["imap_port"], email_addr, acc["password"])
        if err:
            print(f"    FAILED: {err}")
            continue

        try:
            stats = scan_account(imap, email_addr, provider, days)
            for k in totals:
                totals[k] += stats[k]
        finally:
            try:
                imap.logout()
            except:
                pass

        time.sleep(0.3)

    print(f"\n{'=' * 70}")
    print(f"TOTALS: {totals['total']} emails — "
          f"{totals['autoreply']} autoreplies, {totals['application']} applications, "
          f"{totals['normal']} normal, {totals['errors']} errors")


# =============================================================================
# MAIN
# =============================================================================

def main():
    parser = argparse.ArgumentParser(description="Email sorter & autoresponder for all accounts")
    parser.add_argument("--sort-only", action="store_true", help="Only sort emails (no autoresponder setup)")
    parser.add_argument("--setup-only", action="store_true", help="Only create folders + autoresponders")
    parser.add_argument("--status", action="store_true", help="Show current state of all accounts")
    parser.add_argument("--scan", action="store_true", help="List every email in INBOX with classification (read-only)")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without executing")
    parser.add_argument("--days", type=int, default=7, help="Process emails from last N days (default: 7)")
    parser.add_argument("--account", type=str, help="Process single account (email address)")
    parser.add_argument("--no-reply", action="store_true", help="Skip SMTP auto-replies")
    parser.add_argument("--gmail-only", action="store_true", help="Only process Gmail accounts")
    parser.add_argument("--yahoo-only", action="store_true", help="Only process Yahoo accounts")
    parser.add_argument("--a2-only", action="store_true", help="Only process A2 Hosting accounts")
    args = parser.parse_args()

    if args.status:
        run_status()
        return

    accounts = get_all_accounts()

    # Filter by provider
    if args.gmail_only:
        accounts = [a for a in accounts if a["provider"] == "gmail"]
    elif args.yahoo_only:
        accounts = [a for a in accounts if a["provider"] == "yahoo"]
    elif args.a2_only:
        accounts = [a for a in accounts if a["provider"] == "a2"]

    # Filter to single account if specified
    if args.account:
        accounts = [a for a in accounts if a["email"] == args.account]
        if not accounts:
            print(f"Account not found: {args.account}")
            sys.exit(1)

    if args.scan:
        run_scan(accounts, args.days)
        return

    do_sort = not args.setup_only
    do_reply = not args.no_reply and not args.setup_only
    do_autoresponders = not args.sort_only

    mode = "DRY RUN" if args.dry_run else "LIVE"
    print("=" * 70)
    print(f"EMAIL SORTER ({mode}) — {len(accounts)} accounts, last {args.days} days")
    print("=" * 70)

    results = {"ok": 0, "fail": 0}

    for acc in accounts:
        ok = process_account(acc, args.days, args.dry_run, sort=do_sort, reply=do_reply)
        results["ok" if ok else "fail"] += 1
        time.sleep(0.3)

    print(f"\n--- RESULTS ---")
    print(f"Success: {results['ok']} | Failed: {results['fail']} | Total: {results['ok'] + results['fail']}")

    # Set up cPanel autoresponders
    if do_autoresponders:
        setup_cpanel_autoresponders(args.dry_run)

    print("\nDone.")


if __name__ == "__main__":
    main()
