"""
Job title translations, descriptions, and fake company names for ANOFM PDF.
"""

# Romanian job title -> (English name, short description)
JOB_TRANSLATIONS = {
    "LUCRATOR COMERCIAL": ("Sales Associate", "Assist customers, manage product displays, handle transactions and inventory in retail stores."),
    "AJUTOR BUCATAR": ("Kitchen Helper", "Prepare ingredients, maintain kitchen cleanliness, assist chefs with food preparation and plating."),
    "MANIPULANT MARFURI": ("Warehouse Operative", "Load, unload, and move goods in warehouses. Operate basic equipment and organize storage areas."),
    "MUNCITOR NECALIFICAT LA DEMOLAREA CLADIRILOR, CAPTUSELI ZIDARIE, PLACI MOZAIC, FAIANTA, GRESIE, PARCHET": ("Construction Worker", "Perform demolition, remove flooring and wall tiles, prepare sites for renovation. Physical work in construction environments."),
    "Conducator auto transport rutier de marfuri": ("Truck Driver (Cat. C/CE)", "Drive heavy goods vehicles for freight transport. Responsible for loading, delivery schedules, and vehicle maintenance."),
    "MUNCITOR NECALIFICAT LA ASAMBLAREA, MONTAREA PIESELOR": ("Assembly Worker", "Assemble and mount parts and components on production lines. Follow technical instructions for product assembly."),
    "SOFER DE AUTOTURISME SI CAMIONETE": ("Van/Car Driver", "Drive cars and light vans for deliveries and transport. Maintain vehicle and follow delivery routes."),
    "FEMEIE DE SERVICIU": ("Cleaning Staff", "Clean and maintain offices, buildings, and facilities. Ensure hygiene standards are met in all areas."),
    "AGENT DE VANZARI": ("Sales Agent", "Promote and sell products/services to clients. Build customer relationships and achieve sales targets."),
    "VANZATOR": ("Shop Assistant", "Serve customers in retail stores, manage cash register, arrange merchandise, and provide product information."),
    "LUCRATOR BUCATARIE (SPALATOR VASE MARI)": ("Dishwasher / Kitchen Worker", "Wash dishes, pots, and kitchen equipment. Maintain kitchen hygiene and assist with basic food prep tasks."),
    "SUDOR": ("Welder", "Join metal parts using welding equipment (MIG, TIG, arc). Read technical drawings and ensure weld quality standards."),
    "LACATUS MECANIC": ("Mechanical Fitter", "Assemble, install, and repair mechanical equipment. Read blueprints and use precision tools for fitting work."),
    "MUNCITOR NECALIFICAT LA SPARGEREA SI TAIEREA MATERIALELOR DE CONSTRUCTII": ("Construction Labourer", "Break and cut construction materials. Assist with site preparation, concrete work, and material handling."),
    "AMBALATOR MANUAL": ("Manual Packer", "Pack products by hand into boxes and containers. Label packages, check quality, and prepare for shipment."),
    "MECANIC AUTO": ("Auto Mechanic", "Diagnose, repair, and maintain vehicles. Perform engine, brake, and suspension work using diagnostic tools."),
    "CURIER": ("Courier / Delivery Driver", "Deliver packages and documents to customers. Plan routes, collect signatures, and handle returns."),
    "BUCATAR": ("Cook / Chef", "Prepare meals according to menus and recipes. Manage food safety, kitchen inventory, and cooking stations."),
    "OPERATOR LA MASINI-UNELTE CU COMANDA NUMERICA": ("CNC Machine Operator", "Operate computer-controlled machines for cutting and shaping metal. Program CNC settings and monitor output quality."),
    "OSPATAR (CHELNER)": ("Waiter / Server", "Take orders, serve food and drinks, provide excellent customer service in restaurants and hospitality venues."),
    "MUNCITOR NECALIFICAT IN INDUSTRIA CONFECTIILOR": ("Garment Worker", "Perform basic tasks in clothing production. Cut fabric, assist with sewing, and handle finished garments."),
    "STIVUITORIST": ("Forklift Operator", "Operate forklifts to move, load, and stack materials in warehouses. Maintain safety protocols and organize storage."),
    "AGENT CURATENIE CLADIRI SI MIJLOACE DE TRANSPORT": ("Building Cleaner", "Clean commercial buildings, offices, and transport vehicles. Use cleaning equipment and maintain hygiene standards."),
    "UCENIC": ("Apprentice", "Learn trade skills under supervision. Assist qualified workers while gaining practical experience in the profession."),
    "ELECTRICIAN DE INTRETINERE SI REPARATII": ("Maintenance Electrician", "Install, repair, and maintain electrical systems in buildings and industrial facilities. Troubleshoot faults."),
    "CASIER": ("Cashier", "Handle cash transactions, process payments, operate POS systems, and provide customer service at checkout."),
    "MASINIST LA MASINI PENTRU TERASAMENTE (IFRONIST)": ("Excavator Operator", "Operate heavy earthmoving machinery for excavation, grading, and site preparation on construction projects."),
    "TAMPLAR UNIVERSAL": ("General Carpenter", "Build and repair wooden structures, furniture, and fittings. Read plans, measure, cut, and assemble wood products."),
    "DULGHER (EXCLUSIV RESTAURATOR)": ("Construction Carpenter", "Build wooden formwork, scaffolding, and structural elements on construction sites. Work with timber framing."),
    "ZIDAR ROSAR-TENCUITOR": ("Bricklayer / Plasterer", "Build walls with bricks and blocks, apply plaster and render. Ensure structural quality and surface finish."),
    "INGRIJITOR CLADIRI": ("Building Caretaker", "Maintain building facilities, perform minor repairs, handle cleaning, and ensure building security and upkeep."),
    "AJUTOR OSPATAR": ("Assistant Waiter", "Support waiters with serving food and drinks, clearing tables, setting up dining areas, and assisting guests."),
    "MUNCITOR NECALIFICAT LA AMBALAREA PRODUSELOR SOLIDE SI SEMISOLIDE": ("Packing Worker", "Pack solid and semi-solid products into containers. Operate basic packing equipment and check product quality."),
    "GESTIONAR DEPOZIT": ("Warehouse Supervisor", "Manage warehouse inventory, coordinate stock movements, supervise staff, and ensure efficient storage operations."),
    "BRUTAR": ("Baker", "Prepare bread, pastries, and baked goods. Mix dough, operate ovens, and maintain bakery hygiene standards."),
    "CONFECTIONER-ASAMBLOR ARTICOLE DIN TEXTILE": ("Textile Assembler", "Assemble textile products by sewing, cutting, and joining fabric pieces. Operate sewing machines and quality check."),
    "INSTALATOR INSTALATII TEHNICO-SANITARE SI DE GAZE": ("Plumber / Gas Fitter", "Install and repair plumbing, sanitary, and gas systems in buildings. Read technical plans and ensure safety compliance."),
    "DIRECTOR MAGAZIN": ("Store Manager", "Manage retail store operations, supervise staff, control inventory, achieve sales targets, and ensure customer satisfaction."),
    "ELECTRICIAN IN CONSTRUCTII": ("Construction Electrician", "Install electrical wiring, fixtures, and systems in new buildings and renovation projects. Follow electrical codes."),
    "INGINER CONSTRUCTII CIVILE, INDUSTRIALE SI AGRICOLE": ("Civil Engineer", "Design and supervise construction projects. Manage building plans, site inspections, and compliance with regulations."),
    "LUCRATOR GESTIONAR": ("Stock Clerk", "Manage inventory records, receive goods, organize storage, and prepare orders for dispatch in warehouses."),
    "FIERAR BETONIST": ("Rebar Worker", "Cut, bend, and install steel reinforcement bars for concrete structures. Read construction plans and tie rebar."),
    "MECANIC UTILAJ": ("Equipment Mechanic", "Repair and maintain industrial machinery and equipment. Diagnose faults, replace parts, and perform preventive maintenance."),
    "INGINER MECANIC": ("Mechanical Engineer", "Design and oversee mechanical systems and equipment. Manage production processes and technical projects."),
    "OPERATOR LA MASINI-UNELTE SEMIAUTOMATE SI AUTOMATE": ("Machine Operator", "Operate semi-automatic and automatic production machines. Monitor output, adjust settings, and maintain quality."),
    "MUNCITOR NECALIFICAT IN AGRICULTURA": ("Farm Worker", "Perform agricultural tasks: planting, harvesting, weeding, and caring for crops. Operate basic farm tools."),
    "CAMERISTA HOTEL": ("Hotel Housekeeper", "Clean and prepare hotel rooms, change linens, restock supplies, and maintain guest room standards."),
    "ZUGRAV": ("Painter", "Apply paint, wallpaper, and coatings to walls and surfaces. Prepare surfaces, mix paints, and ensure quality finish."),
    "INGRIJITOR ANIMALE": ("Animal Caretaker", "Feed, clean, and care for animals on farms or facilities. Monitor animal health and maintain living areas."),
    "MONTATOR SUBANSAMBLE": ("Sub-Assembly Fitter", "Assemble sub-components and modules on production lines. Follow assembly instructions and verify quality."),
    "BARMAN": ("Bartender", "Prepare and serve drinks, manage bar inventory, maintain cleanliness, and provide customer service at bars."),
    "ELECTRICIAN AUTO": ("Auto Electrician", "Diagnose and repair vehicle electrical systems. Work on wiring, batteries, alternators, and electronic components."),
    "MUNCITOR NECALIFICAT LA INTRETINEREA DE DRUMURI, SOSELE, PODURI, BARAJE": ("Road Maintenance Worker", "Maintain roads, bridges, and infrastructure. Perform repairs, cleaning, and seasonal maintenance tasks."),
    "OPERATOR INTRODUCERE, VALIDARE SI PRELUCRARE DATE": ("Data Entry Operator", "Input, validate, and process data in computer systems. Ensure accuracy and maintain database records."),
    "PATISER": ("Pastry Chef", "Prepare pastries, cakes, and desserts. Work with dough, creams, and decorations in bakery or restaurant settings."),
    "MENAJERA": ("Housekeeper", "Perform domestic cleaning, laundry, and household maintenance. Ensure living spaces are clean and organized."),
    "ASFALTATOR": ("Asphalt Worker", "Lay and compact asphalt for roads and surfaces. Operate paving equipment and ensure smooth, durable finishes."),
    "ASISTENT MANAGER": ("Assistant Manager", "Support management with daily operations, staff coordination, reporting, and customer relations."),
    "Conducator auto transport rutier de persoane": ("Bus/Passenger Driver", "Drive buses or minibuses for passenger transport. Ensure safety, follow routes, and provide good service."),
    "PIZZAR": ("Pizza Maker", "Prepare pizza dough, add toppings, operate pizza ovens, and maintain kitchen cleanliness in pizzerias."),
    "CONFECTIONER ARTICOLE DIN PIELE SI INLOCUITORI": ("Leather Goods Worker", "Cut, sew, and assemble leather products. Operate industrial sewing machines for bags, shoes, and accessories."),
    "TINICHIGIU CAROSIER": ("Panel Beater", "Repair vehicle body panels, straighten dents, and prepare surfaces for painting in auto body shops."),
    "CONTROLOR CALITATE": ("Quality Controller", "Inspect products and processes for quality compliance. Document defects and ensure standards are met."),
    "VOPSITOR AUTO": ("Auto Painter", "Apply paint and coatings to vehicle bodies. Prepare surfaces, mix paints, and use spray equipment."),
    "CONTABIL": ("Accountant", "Manage financial records, process invoices, prepare reports, and ensure compliance with accounting regulations."),
    "LACATUS MECANIC DE INTRETINERE SI REPARATII UNIVERSALE": ("Maintenance Fitter", "Perform general mechanical maintenance and repairs on industrial equipment. Troubleshoot and replace components."),
    "INCARCATOR-DESCARCATOR": ("Loader / Unloader", "Load and unload goods from trucks, containers, and storage areas. Handle materials safely and efficiently."),
    "LACATUS CONSTRUCTII METALICE SI NAVALE": ("Structural Metalworker", "Fabricate and assemble metal structures for construction and shipbuilding. Weld, cut, and fit steel components."),
    "OPERATOR CONFECTIONER INDUSTRIAL IMBRACAMINTE DIN TESATURI, TRICOTAJE, MATERIALE SINTETICE": ("Industrial Sewing Operator", "Operate industrial sewing machines to produce clothing from fabrics, knitwear, and synthetic materials."),
    "FAIANTAR": ("Tile Setter", "Install ceramic tiles, faience, and mosaic on walls and floors. Prepare surfaces, cut tiles, and apply grout."),
    "ELECTRICIAN ECHIPAMENTE ELECTRICE SI ENERGETICE": ("Industrial Electrician", "Install and maintain electrical equipment in industrial and energy facilities. Handle high-voltage systems safely."),
    "ZIDAR PIETRAR": ("Stonemason", "Build and repair stone walls and structures. Cut, shape, and lay natural stone for construction and decoration."),
    "MANAGER": ("Manager", "Lead teams and departments. Plan operations, manage budgets, make strategic decisions, and achieve business goals."),
    "COFETAR": ("Confectioner", "Prepare sweets, chocolates, and confectionery products. Work with sugar, chocolate, and decorative techniques."),
    "MAGAZINER": ("Storekeeper", "Manage warehouse stock, receive deliveries, issue materials, maintain records, and organize storage spaces."),
    "INSTALATOR APA, CANAL": ("Water/Sewage Installer", "Install and repair water supply and sewage systems. Work with pipes, fittings, and drainage infrastructure."),
    "INGRIJITOR SPATII HOTELIERE": ("Hotel Attendant", "Maintain cleanliness in hotel common areas, lobbies, corridors, and facilities. Ensure guest comfort."),
    "CONFECTIONER, PRELUCRATOR IN INDUSTRIA TEXTILA": ("Textile Worker", "Process and manufacture textile products. Operate looms, cutting machines, and finishing equipment."),
    "VOPSITOR INDUSTRIAL": ("Industrial Painter", "Apply protective and decorative coatings to industrial equipment and structures using spray and brush techniques."),
    "MONTATOR PLACAJE INTERIOARE SI EXTERIOAR": ("Wall Cladding Installer", "Install interior and exterior wall panels, cladding, and facade systems on buildings."),
    "MONTATOR PERETI SI PLAFOANE DIN GHIPS-CA": ("Drywall Installer", "Install plasterboard walls and ceilings. Frame, cut, fit, and finish drywall in construction projects."),
    "COMISIONER": ("Order Picker", "Pick and prepare customer orders in warehouses. Use scanning equipment and organize items for shipping."),
    "RECEPTIONER DE HOTEL": ("Hotel Receptionist", "Welcome guests, manage check-in/out, handle reservations, and provide information about hotel services."),
    "SUDOR CU ARC ELECTRIC ACOPERIT SUB STRAT DE FLUX": ("Arc Welder (SAW)", "Perform submerged arc welding on heavy steel structures. Ensure strong, clean welds meeting technical specifications."),
    "SUDOR CU ARC ELECTRIC CU ELECTROD FUZIBIL IN MEDIU DE GAZ PROTECTOR": ("MIG/MAG Welder", "Weld metal components using MIG/MAG gas-shielded process. Work on industrial and construction projects."),
    "TUBULATOR NAVAL": ("Ship Pipe Fitter", "Install and repair piping systems in ships. Cut, bend, and weld pipes for marine vessel construction."),
    "CROITOR": ("Tailor", "Cut, sew, and alter clothing. Take measurements, follow patterns, and create custom garments."),
    "SPALATOR VEHICULE": ("Vehicle Washer", "Clean vehicles inside and out using washing equipment. Polish, vacuum, and detail cars and trucks."),
    "AGENT DE SECURITATE": ("Security Guard", "Monitor premises, control access, patrol areas, and ensure safety and security of people and property."),
}

# Default description for unmapped titles
DEFAULT_DESCRIPTION = "Perform assigned tasks according to job requirements. Follow safety procedures and work instructions. Full training provided."

# Fake company name pools by sector
COMPANY_NAMES = {
    "Construction & Installation": [
        "Euroconst Group SRL", "Atlas Building Solutions", "Carpathia Construction SA",
        "Danube Builders International", "RomBuild Engineering", "Moldavia Construction",
        "TransEuropa Construct", "Balkan Building Works", "Primus Construct SRL",
        "Nova Infrastructure Group", "Apex Construction Romania", "Delta Build Partners",
        "Continental Structures SA", "Meridian Construction", "Summit Building Corp",
        "Horizon Construct SRL", "Fortis Engineering Group", "Pioneer Build Solutions",
        "Omega Construction SA", "Vanguard Builders SRL",
    ],
    "Production & Logistics": [
        "EuroProd Manufacturing SRL", "Continental Components SA", "Prodex Industries",
        "TechLine Production Group", "Balkan Assembly Solutions", "RomFactory International",
        "Precision Parts Manufacturing", "Global Production Systems", "Alpine Industries SRL",
        "NovaTech Manufacturing", "Integra Production SA", "FlexProd Solutions",
        "CoreTech Industries", "Meridian Manufacturing", "Vertex Production Group",
        "Quantum Assembly SRL", "ProLine Industries SA", "EastWest Manufacturing",
        "Titan Production Corp", "Stellar Industries SRL",
    ],
    "Restaurants": [
        "Grand Bistro Restaurant Group", "City Dining Collection", "EuroTaste Restaurants",
        "Bella Cucina SRL", "Golden Fork Group", "Sapori d'Europa",
        "Chef's Table International", "Mediterranean Kitchen Group", "Urban Eats Romania",
        "La Terrasse Restaurant", "Royal Dining SRL", "Fresh & Fast Group",
        "The Olive Garden Romania", "Gastro Palace SRL", "Premier Dining Collection",
    ],
    "Tourism & Food Service": [
        "Grand Hotel Europa", "Belvedere Hospitality Group", "Royal Palace Hotels",
        "Carpathian Resorts SA", "Continental Hotel Group", "Adriatic Tourism SRL",
        "Paradise Hospitality", "Crystal Hotel Management", "Panorama Resort Group",
        "Ambassador Hotel Chain", "Prestige Catering Services", "Alpine Lodge Hotels",
    ],
    "Transport & Courier": [
        "EuroTransport Logistics", "Rapid Delivery Services", "Continental Freight SRL",
        "FastTrack Courier Romania", "Balkan Transport Group", "SpeedLine Logistics",
        "RomCargo International", "Express Delivery Solutions", "TransAlpine Logistics",
        "Meridian Transport SA", "CrossBorder Freight SRL", "ProLog Transport Group",
        "Velocity Courier Services", "FleetLine Logistics SA", "Continental Express SRL",
    ],
    "Agriculture": [
        "Green Valley Farms", "EuroAgri Production SRL", "Harvest Fields Romania",
        "Danube Agricultural Group", "Fresh Produce International", "Natural Farms SA",
        "Continental Agriculture", "Golden Harvest SRL", "Fertile Plains Group",
        "AgroRomania International", "Valley Fresh Farms", "EcoGrow Agriculture",
    ],
    "Cleaning & Childcare": [
        "Crystal Clean Services", "ProClean Romania SRL", "SparkleWash Group",
        "EuroClean International", "FreshStart Cleaning", "BrightSpace Services",
        "PureClean Solutions SA", "Sterling Cleaning Group", "CleanPro Romania",
    ],
    "Garment Manufacturing": [
        "EuroFashion Manufacturing", "TextilPro Industries SRL", "Continental Garments SA",
        "StitchLine Production", "Fashion Works Romania", "ThreadMaster Industries",
        "Premier Textiles SRL", "Elegant Garments Group", "ProStyle Manufacturing",
    ],
    "Auto Service & Mechanics": [
        "AutoPro Service Center", "EuroMech Automotive SRL", "Continental Auto Service",
        "ProFix Auto Group", "MasterTech Automotive", "RapidFix Service Center",
        "Premium Auto Care SRL", "DriveWell Service Group", "AutoElite Romania",
    ],
    "Furniture Production": [
        "WoodCraft Industries SRL", "EuroFurniture Production", "ArtWood Manufacturing",
        "Continental Furniture SA", "MasterWood Group", "Premium Woodworks SRL",
        "ForestLine Production", "Elegance Furniture Group", "TimberTech Industries",
    ],
    "Commerce & Retail": [
        "EuroRetail Group SRL", "Continental Markets SA", "MegaStore Romania",
        "ProCommerce International", "FreshMart Romania", "GlobalShop Group",
        "PrimeRetail Solutions", "MarketPlace Romania SRL", "ValueStore Chain",
    ],
    "Other": [
        "EuroCorp Services SRL", "Continental Business Group", "ProWork Solutions SA",
        "Meridian Business Services", "Global Workforce SRL", "Alliance Group Romania",
        "Premier Services International", "Vertex Business Solutions", "CrossPoint Group",
    ],
}
