#!/usr/bin/env python3
"""
Migrate Campaign to Raspi

Moves email campaigns from raspibig (UNIFIED/PostgreSQL) to raspi (cron/CSV).
Handles: contacts export, template copy, sender script, state setup, cron, dashboard update.

Usage:
    python3 migrate_campaign_to_raspi.py --config /path/to/campaign.json
    python3 migrate_campaign_to_raspi.py --campaign CAMPAIGN_NAME --dry-run
    python3 migrate_campaign_to_raspi.py --list  # Show migratable campaigns

Example:
    python3 migrate_campaign_to_raspi.py --campaign tudor_anofm --dry-run
    python3 migrate_campaign_to_raspi.py --campaign tudor_anofm --execute
"""

import os
import sys
import json
import argparse
import subprocess
import shutil
from datetime import datetime
from pathlib import Path

# Paths
UNIFIED_DIR = "/opt/ACTIVE/EMAIL/CAMPAIGNS/UNIFIED"
PIPELINE_JSON = f"{UNIFIED_DIR}/pipeline.json"
RASPI_HOST = "192.168.100.20"
RASPI_CAMPAIGNS_DIR = "/opt/EMAIL/CAMPAIGNS"
SENDER_TEMPLATE = "/opt/ACTIVE/INFRA/SKILLS/templates/raspi_campaign_sender.py"

# Sender script template (embedded)
SENDER_SCRIPT_TEMPLATE = '''#!/usr/bin/env python3
"""
{campaign_name} Campaign Sender (raspi)

Auto-generated by migrate_campaign_to_raspi.py on {date}
Migrated from: raspibig unified-orchestrator

Usage:
    python3 {script_name} --test --limit 3
    python3 {script_name} --limit 50
    python3 {script_name} --status
    python3 {script_name} --force  # Override business hours
"""

import os
import sys
import csv
import json
import smtplib
import argparse
import random
import time
from pathlib import Path
from datetime import datetime, date
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

# Load environment
load_dotenv('/opt/EMAIL/.env')

# Campaign config
CAMPAIGN_NAME = "{campaign_name}"
CAMPAIGN_DIR = Path(__file__).parent
CONTACTS_DIR = CAMPAIGN_DIR / "contacts"
TEMPLATES_DIR = CAMPAIGN_DIR / "templates"
LOGS_DIR = CAMPAIGN_DIR / "logs"
STATE_FILE = CAMPAIGN_DIR / ".{state_file_name}_state.json"
SENT_LOG = CAMPAIGN_DIR / "sent_log.json"
DNC_FILE = CAMPAIGN_DIR / "dnc.txt"
STATUS_FILE = CAMPAIGN_DIR / "status.json"

# Sender config
GMAIL_USER = os.getenv('{gmail_env_user}', '')
GMAIL_PASS = os.getenv('{gmail_env_pass}', '')
GMAIL_LIMIT = {gmail_limit}

BREVO_API_KEY = os.getenv('{brevo_env_key}', '')
BREVO_SENDER = "{brevo_sender}"
BREVO_NAME = "{brevo_name}"
BREVO_LIMIT = {brevo_limit}

# Timing
DELAY_MIN = {delay_min}
DELAY_MAX = {delay_max}

# Business hours
BUSINESS_HOURS_START = {bh_start}
BUSINESS_HOURS_END = {bh_end}
BUSINESS_DAYS = {bh_days}  # 0=Monday, 6=Sunday


def load_state():
    if STATE_FILE.exists():
        with open(STATE_FILE) as f:
            return json.load(f)
    return {{"last_date": None, "gmail_today": 0, "brevo_today": 0, "total_sent": 0}}


def save_state(state):
    with open(STATE_FILE, 'w') as f:
        json.dump(state, f, indent=2)


def load_sent_log():
    if SENT_LOG.exists():
        with open(SENT_LOG) as f:
            return set(json.load(f))
    return set()


def save_sent_log(sent):
    with open(SENT_LOG, 'w') as f:
        json.dump(list(sent), f)


def load_dnc():
    dnc = set()
    if DNC_FILE.exists():
        with open(DNC_FILE) as f:
            for line in f:
                email = line.strip().lower()
                if email and '@' in email:
                    dnc.add(email)
    return dnc


def is_business_hours():
    now = datetime.now()
    if now.weekday() not in BUSINESS_DAYS:
        return False, f"Weekend (day {{now.weekday()}})"
    if now.hour < BUSINESS_HOURS_START:
        return False, f"Before {{BUSINESS_HOURS_START}}:00"
    if now.hour >= BUSINESS_HOURS_END:
        return False, f"After {{BUSINESS_HOURS_END}}:00"
    return True, "OK"


def load_contacts():
    contacts = []
    for csv_file in CONTACTS_DIR.glob("*.csv"):
        with open(csv_file, newline='', encoding='utf-8', errors='ignore') as f:
            reader = csv.DictReader(f)
            for row in reader:
                email = row.get('email', '').strip().lower()
                if email and '@' in email:
                    contacts.append({{
                        'email': email,
                        'company': row.get('company', row.get('company_name', '')),
                        'name': row.get('name', row.get('contact_name', '')),
                        'city': row.get('city', ''),
                        'source_file': csv_file.name
                    }})
    return contacts


def load_template():
    for tpl in TEMPLATES_DIR.glob("*.txt"):
        with open(tpl) as f:
            content = f.read()
        lines = content.split('\\n')
        subject = lines[0].replace('Subject:', '').strip() if lines[0].startswith('Subject:') else "Message"
        body = '\\n'.join(lines[2:]) if len(lines) > 2 else content
        return subject, body
    return "Message", "Hello"


def send_gmail(to_email, subject, body, test=False):
    if test:
        return True, "TEST"
    try:
        msg = MIMEMultipart()
        msg['From'] = f"{{BREVO_NAME}} <{{GMAIL_USER}}>"
        msg['To'] = to_email
        msg['Subject'] = subject
        msg.attach(MIMEText(body, 'plain', 'utf-8'))

        with smtplib.SMTP_SSL('smtp.gmail.com', 465, timeout=30) as server:
            server.login(GMAIL_USER, GMAIL_PASS)
            server.send_message(msg)
        return True, "GMAIL"
    except Exception as e:
        return False, str(e)[:50]


def send_brevo(to_email, subject, body, test=False):
    if test:
        return True, "TEST"
    try:
        import requests
        resp = requests.post(
            'https://api.brevo.com/v3/smtp/email',
            headers={{'api-key': BREVO_API_KEY, 'Content-Type': 'application/json'}},
            json={{
                'sender': {{'email': BREVO_SENDER, 'name': BREVO_NAME}},
                'to': [{{'email': to_email}}],
                'subject': subject,
                'textContent': body
            }},
            timeout=30
        )
        if resp.status_code in (200, 201):
            return True, "BREVO"
        return False, f"HTTP {{resp.status_code}}"
    except Exception as e:
        return False, str(e)[:50]


def get_status_dict(state, contacts, sent_log, dnc):
    bh_ok, bh_reason = is_business_hours()
    contact_files = []
    for csv_file in CONTACTS_DIR.glob("*.csv"):
        with open(csv_file) as f:
            total = sum(1 for _ in f) - 1
        contact_files.append({{'file': csv_file.name, 'total': total, 'remaining': total - len(sent_log)}})

    return {{
        'campaign': CAMPAIGN_NAME,
        'location': 'raspi',
        'status': 'active' if bh_ok else 'outside_hours',
        'business_hours': f"{{BUSINESS_HOURS_START}}:00-{{BUSINESS_HOURS_END}}:00 Mon-Fri",
        'is_business_hours': bh_ok,
        'business_hours_reason': bh_reason,
        'last_date': state.get('last_date'),
        'gmail_today': state.get('gmail_today', 0),
        'gmail_limit': GMAIL_LIMIT,
        'brevo_today': state.get('brevo_today', 0),
        'brevo_limit': BREVO_LIMIT,
        'total_sent': state.get('total_sent', 0),
        'sent_log_count': len(sent_log),
        'dnc_count': len(dnc),
        'contacts': contact_files,
        'remaining': sum(c['remaining'] for c in contact_files),
        'updated': datetime.now().isoformat()
    }}


def export_status(state, contacts, sent_log, dnc):
    status = get_status_dict(state, contacts, sent_log, dnc)
    with open(STATUS_FILE, 'w') as f:
        json.dump(status, f, indent=2)


def main():
    parser = argparse.ArgumentParser(description=f'{{CAMPAIGN_NAME}} Campaign Sender')
    parser.add_argument('--limit', type=int, default=50, help='Max emails to send')
    parser.add_argument('--test', action='store_true', help='Dry run mode')
    parser.add_argument('--force', action='store_true', help='Override business hours')
    parser.add_argument('--status', action='store_true', help='Show status and exit')
    args = parser.parse_args()

    # Ensure directories
    LOGS_DIR.mkdir(exist_ok=True)

    # Load data
    state = load_state()
    sent_log = load_sent_log()
    dnc = load_dnc()
    contacts = load_contacts()

    # Reset daily counters if new day
    today = date.today().isoformat()
    if state.get('last_date') != today:
        state['last_date'] = today
        state['gmail_today'] = 0
        state['brevo_today'] = 0

    # Export status for dashboard
    export_status(state, contacts, sent_log, dnc)

    if args.status:
        status = get_status_dict(state, contacts, sent_log, dnc)
        print(json.dumps(status, indent=2))
        return

    # Business hours check
    if not args.force:
        bh_ok, bh_reason = is_business_hours()
        if not bh_ok:
            print(f"Outside business hours: {{bh_reason}}")
            print("Use --force to override")
            return

    # Filter contacts
    to_send = [c for c in contacts if c['email'] not in sent_log and c['email'] not in dnc]
    random.shuffle(to_send)

    print(f"=== {{CAMPAIGN_NAME}} ===")
    print(f"Contacts: {{len(contacts)}}, Sent: {{len(sent_log)}}, DNC: {{len(dnc)}}, To send: {{len(to_send)}}")
    print(f"Gmail: {{state['gmail_today']}}/{{GMAIL_LIMIT}}, Brevo: {{state['brevo_today']}}/{{BREVO_LIMIT}}")

    if not to_send:
        print("No contacts to send")
        return

    subject_tpl, body_tpl = load_template()
    sent_count = 0

    for i, contact in enumerate(to_send[:args.limit]):
        # Check limits
        gmail_available = state['gmail_today'] < GMAIL_LIMIT
        brevo_available = state['brevo_today'] < BREVO_LIMIT

        if not gmail_available and not brevo_available:
            print("Daily limits reached")
            break

        # Choose sender (Gmail for Yahoo/Hotmail, Brevo for others)
        email = contact['email']
        use_gmail = gmail_available and any(d in email for d in ['yahoo.', 'hotmail.', 'outlook.', 'live.'])

        if not use_gmail and not brevo_available:
            use_gmail = gmail_available
        if use_gmail and not gmail_available:
            use_gmail = False

        if not use_gmail and not brevo_available:
            print("No sender available")
            break

        # Personalize
        subject = subject_tpl.replace('{{company_name}}', contact.get('company', ''))
        subject = subject.replace('{{company}}', contact.get('company', ''))
        body = body_tpl.replace('{{company_name}}', contact.get('company', ''))
        body = body.replace('{{company}}', contact.get('company', ''))
        body = body.replace('{{name}}', contact.get('name', ''))
        body = body.replace('{{city}}', contact.get('city', ''))

        # Send
        if use_gmail:
            success, method = send_gmail(email, subject, body, args.test)
        else:
            success, method = send_brevo(email, subject, body, args.test)

        if success:
            sent_log.add(email)
            state['total_sent'] += 1
            if use_gmail:
                state['gmail_today'] += 1
            else:
                state['brevo_today'] += 1
            sent_count += 1
            print(f"[{{i+1}}/{{args.limit}}] {{email}} via {{method}}")

            # Log
            log_file = LOGS_DIR / f"sent_{{today}}.log"
            with open(log_file, 'a') as f:
                f.write(f"{{datetime.now().isoformat()}}|{{email}}|{{method}}|{{contact.get('company', '')}}\\n")
        else:
            print(f"[{{i+1}}/{{args.limit}}] FAILED {{email}}: {{method}}")

        # Save state after each send
        save_state(state)
        save_sent_log(sent_log)
        export_status(state, contacts, sent_log, dnc)

        # Delay (skip on last)
        if i < min(len(to_send), args.limit) - 1:
            delay = random.randint(DELAY_MIN, DELAY_MAX)
            if not args.test:
                print(f"Waiting {{delay}}s...")
                time.sleep(delay)

    print(f"\\nSent {{sent_count}} emails")
    print(f"Gmail: {{state['gmail_today']}}/{{GMAIL_LIMIT}}, Brevo: {{state['brevo_today']}}/{{BREVO_LIMIT}}")


if __name__ == '__main__':
    main()
'''


def load_pipeline_config():
    """Load pipeline.json config."""
    with open(PIPELINE_JSON) as f:
        return json.load(f)


def save_pipeline_config(config):
    """Save pipeline.json config."""
    with open(PIPELINE_JSON, 'w') as f:
        json.dump(config, f, indent=2)


def get_migratable_campaigns():
    """List campaigns that can be migrated."""
    config = load_pipeline_config()
    campaigns = config.get('campaigns', {})
    migratable = []
    for name, cfg in campaigns.items():
        if cfg.get('status') == 'MIGRATED_TO_RASPI':
            continue
        if 'db' not in cfg:
            continue
        migratable.append({
            'name': name,
            'db': cfg['db'].get('dbname'),
            'table': cfg.get('tables', {}).get('contacts', 'contacts'),
            'daily_capacity': cfg.get('daily_capacity', 0)
        })
    return migratable


def export_contacts(campaign_cfg, output_file, dry_run=False):
    """Export contacts from PostgreSQL to CSV."""
    import psycopg2

    db = campaign_cfg['db']
    tables = campaign_cfg.get('tables', {})
    contacts_table = tables.get('contacts', 'contacts')

    # Build query
    col_email = tables.get('col_email', 'email')
    col_company = tables.get('col_company', tables.get('col_name', 'company_name'))
    col_city = tables.get('col_city', 'city')

    query = f"""
        SELECT {col_email} as email, {col_company} as company, {col_city} as city
        FROM {contacts_table}
        WHERE {col_email} IS NOT NULL AND {col_email} != ''
    """

    # Add filter if present
    if 'filter' in campaign_cfg:
        query += f" AND ({campaign_cfg['filter']})"

    if dry_run:
        print(f"  [DRY RUN] Would export from {db['dbname']}.{contacts_table}")
        print(f"  Query: {query[:200]}...")
        return 0

    conn = psycopg2.connect(**db)
    cur = conn.cursor()
    cur.execute(query)
    rows = cur.fetchall()
    conn.close()

    with open(output_file, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['email', 'company', 'city'])
        for row in rows:
            writer.writerow(row)

    return len(rows)


def run_ssh(cmd, dry_run=False):
    """Run command on raspi via SSH."""
    full_cmd = f"ssh -o ConnectTimeout=5 {RASPI_HOST} '{cmd}'"
    if dry_run:
        print(f"  [DRY RUN] {full_cmd}")
        return True, ""
    result = subprocess.run(full_cmd, shell=True, capture_output=True, text=True)
    return result.returncode == 0, result.stdout + result.stderr


def rsync_to_raspi(local_path, remote_path, dry_run=False):
    """Rsync file to raspi."""
    cmd = f"rsync -avz {local_path} {RASPI_HOST}:{remote_path}"
    if dry_run:
        print(f"  [DRY RUN] {cmd}")
        return True
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return result.returncode == 0


def migrate_campaign(campaign_name, campaign_cfg, dry_run=False):
    """Migrate a campaign from raspibig to raspi."""
    print(f"\n{'='*60}")
    print(f"MIGRATING: {campaign_name}")
    print(f"{'='*60}")

    # Derive names
    safe_name = campaign_name.lower().replace(' ', '_').replace('-', '_')
    raspi_dir = f"{RASPI_CAMPAIGNS_DIR}/{safe_name.upper()}"
    script_name = f"{safe_name}_sender.py"
    state_file_name = f"{safe_name}_sender"

    # Extract sender config from campaign
    # These would come from the unified config or sector config
    gmail_env_user = campaign_cfg.get('gmail_env_user', 'GMAIL_USER')
    gmail_env_pass = campaign_cfg.get('gmail_env_pass', 'GMAIL_APP_PASSWORD')
    gmail_limit = campaign_cfg.get('gmail_limit', 100)

    brevo_env_key = campaign_cfg.get('brevo_env_key', 'BREVO_API_KEY')
    brevo_sender = campaign_cfg.get('brevo_sender', 'office@example.com')
    brevo_name = campaign_cfg.get('brevo_name', 'Sender Name')
    brevo_limit = campaign_cfg.get('brevo_limit', 290)

    delay_min = campaign_cfg.get('delay_min', 180)
    delay_max = campaign_cfg.get('delay_max', 240)

    bh_start = campaign_cfg.get('business_hours_start', 8)
    bh_end = campaign_cfg.get('business_hours_end', 18)
    bh_days = campaign_cfg.get('business_days', [0, 1, 2, 3, 4])

    # Step 1: Create directories on raspi
    print("\n[1/7] Creating directories on raspi...")
    run_ssh(f"mkdir -p {raspi_dir}/{{contacts,templates,logs}}", dry_run)

    # Step 2: Export contacts
    print("\n[2/7] Exporting contacts from PostgreSQL...")
    tmp_csv = f"/tmp/{safe_name}_contacts.csv"
    count = export_contacts(campaign_cfg, tmp_csv, dry_run)
    print(f"  Exported {count} contacts")

    # Step 3: Copy contacts to raspi
    print("\n[3/7] Copying contacts to raspi...")
    rsync_to_raspi(tmp_csv, f"{raspi_dir}/contacts/contacts.csv", dry_run)

    # Step 4: Copy template
    print("\n[4/7] Copying template...")
    template_dir = campaign_cfg.get('templates_dir', f"{UNIFIED_DIR}/templates/{safe_name}/")
    template_file = None
    if os.path.isdir(template_dir):
        for tpl in Path(template_dir).glob("*.txt"):
            template_file = str(tpl)
            break

    if template_file:
        rsync_to_raspi(template_file, f"{raspi_dir}/templates/template.txt", dry_run)
    else:
        print(f"  WARNING: No template found in {template_dir}")

    # Step 5: Generate sender script
    print("\n[5/7] Generating sender script...")
    script_content = SENDER_SCRIPT_TEMPLATE.format(
        campaign_name=campaign_name.upper(),
        date=datetime.now().strftime('%Y-%m-%d'),
        script_name=script_name,
        state_file_name=state_file_name,
        gmail_env_user=gmail_env_user,
        gmail_env_pass=gmail_env_pass,
        gmail_limit=gmail_limit,
        brevo_env_key=brevo_env_key,
        brevo_sender=brevo_sender,
        brevo_name=brevo_name,
        brevo_limit=brevo_limit,
        delay_min=delay_min,
        delay_max=delay_max,
        bh_start=bh_start,
        bh_end=bh_end,
        bh_days=str(bh_days)
    )

    tmp_script = f"/tmp/{script_name}"
    if not dry_run:
        with open(tmp_script, 'w') as f:
            f.write(script_content)
    rsync_to_raspi(tmp_script, f"{raspi_dir}/{script_name}", dry_run)
    run_ssh(f"chmod +x {raspi_dir}/{script_name}", dry_run)

    # Step 6: Create wrapper script
    print("\n[6/7] Creating wrapper script...")
    wrapper = f"""#!/bin/bash
cd {raspi_dir}
/opt/venv/bin/python3 {script_name} "$@"
"""
    tmp_wrapper = f"/tmp/run-{safe_name}.sh"
    if not dry_run:
        with open(tmp_wrapper, 'w') as f:
            f.write(wrapper)
    rsync_to_raspi(tmp_wrapper, f"{raspi_dir}/run-{safe_name}.sh", dry_run)
    run_ssh(f"chmod +x {raspi_dir}/run-{safe_name}.sh", dry_run)

    # Step 7: Update pipeline.json
    print("\n[7/7] Updating pipeline.json...")
    if not dry_run:
        config = load_pipeline_config()

        # Mark original campaign as migrated
        if campaign_name in config.get('campaigns', {}):
            config['campaigns'][campaign_name]['status'] = 'MIGRATED_TO_RASPI'
            config['campaigns'][campaign_name]['migrated_date'] = datetime.now().strftime('%Y-%m-%d')
            config['campaigns'][campaign_name]['raspi_path'] = raspi_dir

        # Add to raspi_campaigns
        if 'raspi_campaigns' not in config:
            config['raspi_campaigns'] = {}

        config['raspi_campaigns'][safe_name] = {
            'host': RASPI_HOST,
            'path': f"{raspi_dir}/",
            'script': script_name,
            'status_file': 'status.json',
            'state_file': f'.{state_file_name}_state.json',
            'business_hours': f"{bh_start}:00-{bh_end}:00 Mon-Fri",
            'senders': {
                'gmail': {'email': gmail_env_user, 'limit': gmail_limit},
                'brevo': {'email': brevo_sender, 'limit': brevo_limit}
            },
            'cron': '40 8,12,16 * * *',
            'daily_capacity': gmail_limit + brevo_limit,
            'migrated_from': 'raspibig unified-orchestrator',
            'migrated_date': datetime.now().strftime('%Y-%m-%d')
        }

        save_pipeline_config(config)

    print(f"\n{'='*60}")
    print(f"MIGRATION COMPLETE: {campaign_name}")
    print(f"{'='*60}")
    print(f"\nRaspi location: {raspi_dir}")
    print(f"\nNext steps:")
    print(f"  1. Add credentials to raspi /opt/EMAIL/.env:")
    print(f"     {gmail_env_user}=...")
    print(f"     {gmail_env_pass}=...")
    print(f"     {brevo_env_key}=...")
    print(f"\n  2. Test on raspi:")
    print(f"     ssh raspi '{raspi_dir}/run-{safe_name}.sh --test --limit 3'")
    print(f"\n  3. Add cron job on raspi:")
    print(f"     40 8,12,16 * * * {raspi_dir}/run-{safe_name}.sh --limit 100")
    print(f"\n  4. Restart dashboard:")
    print(f"     sudo systemctl restart pipeline-dashboard")


def main():
    parser = argparse.ArgumentParser(description='Migrate campaign from raspibig to raspi')
    parser.add_argument('--list', action='store_true', help='List migratable campaigns')
    parser.add_argument('--campaign', help='Campaign name to migrate')
    parser.add_argument('--config', help='Campaign config JSON file')
    parser.add_argument('--dry-run', action='store_true', help='Show what would be done')
    parser.add_argument('--execute', action='store_true', help='Actually perform migration')
    args = parser.parse_args()

    if args.list:
        campaigns = get_migratable_campaigns()
        print("Migratable campaigns:")
        print("-" * 60)
        for c in campaigns:
            print(f"  {c['name']}: {c['db']}.{c['table']} ({c['daily_capacity']}/day)")
        return

    if args.campaign:
        config = load_pipeline_config()
        if args.campaign not in config.get('campaigns', {}):
            print(f"Campaign not found: {args.campaign}")
            print("Use --list to see available campaigns")
            sys.exit(1)

        campaign_cfg = config['campaigns'][args.campaign]
        if campaign_cfg.get('status') == 'MIGRATED_TO_RASPI':
            print(f"Campaign {args.campaign} is already migrated")
            sys.exit(1)

        if not args.execute and not args.dry_run:
            print("Use --dry-run to preview or --execute to perform migration")
            sys.exit(1)

        migrate_campaign(args.campaign, campaign_cfg, dry_run=args.dry_run)
        return

    if args.config:
        with open(args.config) as f:
            campaign_cfg = json.load(f)
        name = Path(args.config).stem
        migrate_campaign(name, campaign_cfg, dry_run=args.dry_run)
        return

    parser.print_help()


if __name__ == '__main__':
    main()
